### ISSUE TITLE
elasticsearch fails to deploy successfully

### ISSUE THREAD

**Issue by iatrou** [juju-solutions/bundle-canonical-kubernetes#129]
After the deployment of the bundle, elastic search remains in error state.
juju resolved does not alter its state.

juju status
http://paste.ubuntu.com/23452924/

bundle
http://paste.ubuntu.com/23452922/

/var/log/juju/unit-elasticsearch-1.log
http://paste.ubuntu.com/23452705/

elasticsearch.log
http://paste.ubuntu.com/23452918/

**Comment by chuckbutler** [comment]
This seems like the multicast failed based on 

```
[2016-11-09 22:16:37,835][WARN ][rest.suppressed          ] path: /_cluster/health, params: {}
MasterNotDiscoveredException[null]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$5.onTimeout(TransportMasterNodeAction.java:234)
	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:236)
	at org.elasticsearch.cluster.service.InternalClusterService$NotifyTimeout.run(InternalClusterService.java:804)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

and is supported by the playbook error output

```
failed: [localhost] => {"content": "{\"error\":{\"root_cause\":[{\"type\":\"master_not_discovered_exception\",\"reason\":null}],\"type\":\"master_not_discovered_exception\",\"reason\":null},\"status\":503}", "content_length": "151", "content_type": "application/json; charset=UTF-8", "failed": true, "item": "", "json": {"error": {"reason": null, "root_cause": [{"reason": null, "type": "master_not_discovered_exception"}], "type": "master_not_discovered_exception"}, "status": 503}, "redirected": false, "status": 503}
2016-11-09 21:05:00 INFO peer-relation-changed msg: Status code was not 200
```


I was able to deploy a scaled elasticsearch cluster to AWS without reproducing this bug (using just the elasticsearch bits from the bundle) Without further detail, as to why it happened, I'm unable to reproduce the multicast failure.
