### ISSUE TITLE
etcd charm failure on certificates-relation-changed

### ISSUE THREAD

**Issue by axinojolais** [juju-solutions/bundle-canonical-kubernetes#153]
Hi,

It looks like every time we deploy, there is a transient error with the etcd charm (see logs below). This is transient because juju2 will automatically retry, and the next attempt will work.

However, mojo stops if it ever detects an error, so this is preventing it from completing its run. In all cases, I believe hooks should ideally never fail.

Thank you

```
2016-12-15 13:49:44 INFO juju-log certificates:6: Reactive main running for hook certificates-relation-changed
2016-12-15 13:49:44 INFO juju-log certificates:6: Initializing Leadership Layer (is follower)
2016-12-15 13:49:44 INFO juju-log certificates:6: Invoking reactive handler: hooks/relations/tls-certificates/requires.py:22:changed
2016-12-15 13:49:45 INFO juju-log certificates:6: Invoking reactive handler: reactive/etcd.py:67:set_app_version
2016-12-15 13:49:45 INFO juju-log certificates:6: Invoking reactive handler: reactive/etcd.py:85:prepare_tls_certificates
2016-12-15 13:49:45 INFO juju-log certificates:6: Invoking reactive handler: reactive/tls_client.py:53:store_client
2016-12-15 13:49:45 INFO juju-log certificates:6: Invoking reactive handler: reactive/tls_client.py:32:store_server
2016-12-15 13:49:45 INFO juju-log certificates:6: Writing server certificate to /etc/ssl/etcd/server.crt
2016-12-15 13:49:45 INFO juju-log certificates:6: Writing server key to /etc/ssl/etcd/server.key
2016-12-15 13:49:45 INFO juju-log certificates:6: Invoking reactive handler: reactive/tls_client.py:14:store_ca
2016-12-15 13:49:45 INFO juju-log certificates:6: Invoking reactive handler: reactive/etcd.py:98:spam_ownership_of_tls_certs
2016-12-15 13:49:46 INFO juju-log certificates:6: Invoking reactive handler: reactive/etcd.py:205:send_single_connection_details
2016-12-15 13:49:46 INFO juju-log certificates:6: Invoking reactive handler: reactive/etcd.py:272:register_node_with_leader
2016-12-15 13:49:47 INFO certificates-relation-changed Error:  dial tcp 127.0.0.1:2379: getsockopt: connection refused
2016-12-15 13:49:47 INFO certificates-relation-changed Traceback (most recent call last):
2016-12-15 13:49:47 INFO certificates-relation-changed   File "/var/lib/juju/agents/unit-etcd-1/charm/hooks/certificates-relation-changed", line 19, in <module>
2016-12-15 13:49:47 INFO certificates-relation-changed     main()
2016-12-15 13:49:47 INFO certificates-relation-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
2016-12-15 13:49:47 INFO certificates-relation-changed     bus.dispatch()
2016-12-15 13:49:47 INFO certificates-relation-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
2016-12-15 13:49:47 INFO certificates-relation-changed     _invoke(other_handlers)
2016-12-15 13:49:47 INFO certificates-relation-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
2016-12-15 13:49:47 INFO certificates-relation-changed     handler.invoke()
2016-12-15 13:49:47 INFO certificates-relation-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
2016-12-15 13:49:47 INFO certificates-relation-changed     self._action(*args)
2016-12-15 13:49:47 INFO certificates-relation-changed   File "/var/lib/juju/agents/unit-etcd-1/charm/reactive/etcd.py", line 297, in register_node_with_leader
2016-12-15 13:49:47 INFO certificates-relation-changed     peers = etcdctl.member_list(leader_get('leader_address'))
2016-12-15 13:49:47 INFO certificates-relation-changed   File "lib/etcdctl.py", line 75, in member_list
2016-12-15 13:49:47 INFO certificates-relation-changed     out = self.run("etcdctl member list")
2016-12-15 13:49:47 INFO certificates-relation-changed   File "lib/etcdctl.py", line 139, in run
2016-12-15 13:49:47 INFO certificates-relation-changed     return check_output(split(command)).decode('ascii')
2016-12-15 13:49:47 INFO certificates-relation-changed   File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
2016-12-15 13:49:47 INFO certificates-relation-changed     **kwargs).stdout
2016-12-15 13:49:47 INFO certificates-relation-changed   File "/usr/lib/python3.5/subprocess.py", line 708, in run
2016-12-15 13:49:47 INFO certificates-relation-changed     output=stdout, stderr=stderr)
2016-12-15 13:49:47 INFO certificates-relation-changed subprocess.CalledProcessError: Command '['etcdctl', 'member', 'list']' returned non-zero exit status 4
2016-12-15 13:49:47 ERROR juju.worker.uniter.operation runhook.go:107 hook "certificates-relation-changed" failed: exit status 1
```

**Comment by mbruzek** [comment]
Thanks to @axinojolais for pointing this out. I created an issue on the etcd layer to track this https://github.com/juju-solutions/layer-etcd/issues/70

We recently updated the bundle #152 with a different etcd charm. The bundle has not passed all our testing and has not yet been released to jujucharms.com at this time, but the github repository has been updated. Can you please redeploy with the new bundle and report a reproduction scenario in the etcd issue tracker if you see this error again?

**Comment by axinojolais** [comment]
Hi,

This happens with etcd-21 as well. We use mojo to deploy, but here is what mojo / juju-deployer does :

1. deploy a single unit of the following charms : easyrsa, kubernetes-worker, kubernetes-master, flannel
2. deploy 3 units of etcd, and the nrpe application (subordinate)
3. add 2 units to kubernetes-worker
4. wait for the units to be active/blocked/waiting
4. add relations in this order : 
```
Adding relation etcd <-> nrpe
Adding relation kubernetes-master <-> nrpe
Adding relation kubernetes-worker <-> nrpe
Adding relation kubeapi-load-balancer <-> nrpe
Adding relation easyrsa <-> nrpe
Adding relation etcd:certificates <-> easyrsa:client
Adding relation kubernetes-master:kube-api-endpoint <-> kubeapi-load-balancer:apiserver
Adding relation kubernetes-master:loadbalancer <-> kubeapi-load-balancer:loadbalancer
Adding relation kubernetes-master:cluster-dns <-> kubernetes-worker:kube-dns
Adding relation kubernetes-master:certificates <-> easyrsa:client
Adding relation kubernetes-master:etcd <-> etcd:db
Adding relation kubernetes-master:cni <-> flannel:cni
Adding relation kubernetes-worker:certificates <-> easyrsa:client
Adding relation kubernetes-worker:cni <-> flannel:cni
Adding relation kubernetes-worker:kube-api-endpoint <-> kubeapi-load-balancer:website
Adding relation flannel:etcd <-> etcd:db
Adding relation kubeapi-load-balancer:certificates <-> easyrsa:client
```

Note that each time I've looked, this happened on a single etcd unit only, generally etcd/0 or etcd/1. Also, note that the error is transient and juju2 will auto-resolve it by retrying.

**Comment by chuckbutler** [comment]
This just landed in the master branch of the etcd layer, and will go out with the next release of the charm.

Thanks for your patience and filing the bug, I think we're good to close this bug in anticipation of the next release. All tests have been good on both AWS and GCE.

**Comment by chuckbutler** [comment]
On further thought, it'll be easier to compile release notes if this is left open until its published to the charm store.

**Comment by chuckbutler** [comment]
This was published this morning in the edge channel as etcd-22

There's a companion bundle in the edge channel as cs:~containers/bundle/canonical-kubernetes-16

If you're interested in testing this fix, i'd appreciate any/all early feedback

**Comment by chuckbutler** [comment]
Another bump to this bundle, `cs:~containers/bundle/canonical-kubernetes-17` I managed to publish the -layer- not the -charm- yesterday which caused all kinds of fires to pop up unexpectedly. Good to know we're on par for disaster recovery I suppose :) At least this was an edge channel release, phew.

**Comment by axinojolais** [comment]
I tested the new bundle. I deployed it twice without apparent issue. I checked the etcd unit log manually, and no error there. But the third time, I got an error, still related to etcd, but in the etcd-relation-joined hook of the flannel application.

The error is :
```
2017-01-17 16:09:45 INFO etcd-relation-joined Error:  dial tcp 10.25.62.36:2379: getsockopt: connection refused
2017-01-17 16:09:45 INFO etcd-relation-joined Traceback (most recent call last):
2017-01-17 16:09:45 INFO etcd-relation-joined   File "/var/lib/juju/agents/unit-flannel-3/charm/hooks/etcd-relation-joined", line 19, in <module>
2017-01-17 16:09:45 INFO etcd-relation-joined     main()
2017-01-17 16:09:45 INFO etcd-relation-joined   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
2017-01-17 16:09:45 INFO etcd-relation-joined     bus.dispatch()
2017-01-17 16:09:45 INFO etcd-relation-joined   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
2017-01-17 16:09:45 INFO etcd-relation-joined     _invoke(other_handlers)
2017-01-17 16:09:45 INFO etcd-relation-joined   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
2017-01-17 16:09:45 INFO etcd-relation-joined     handler.invoke()
2017-01-17 16:09:45 INFO etcd-relation-joined   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
2017-01-17 16:09:45 INFO etcd-relation-joined     self._action(*args)
2017-01-17 16:09:45 INFO etcd-relation-joined   File "/var/lib/juju/agents/unit-flannel-3/charm/reactive/flannel.py", line 126, in configure_network
2017-01-17 16:09:45 INFO etcd-relation-joined     check_call(split(cmd))
2017-01-17 16:09:45 INFO etcd-relation-joined   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
2017-01-17 16:09:45 INFO etcd-relation-joined     raise CalledProcessError(retcode, cmd)
2017-01-17 16:09:45 INFO etcd-relation-joined subprocess.CalledProcessError: Command '['etcdctl', '--endpoint', 'https://10.25.62.35:2379,https://10.25.62.36:2379', '--c
ert-file', '/etc/ssl/flannel/client-cert.pem', '--key-file', '/etc/ssl/flannel/client-key.pem', '--ca-file', '/etc/ssl/flannel/client-ca.pem', 'set', '/coreos.com/networ
k/config', '{"Backend": {"Type": "vxlan"}, "Network": "10.1.0.0/16"}']' returned non-zero exit status 4
2017-01-17 16:09:45 ERROR juju.worker.uniter.operation runhook.go:107 hook "etcd-relation-joined" failed: exit status 1
```

I'm going to try to reproduce it.

**Comment by axinojolais** [comment]
After redeploying the cluster 4 times, I have been unable to reproduce this issue. I think it should still probably be handled gracefully though.

**Comment by axinojolais** [comment]
I was able to repro this last error (in the etcd-relation-joined hook of the flannel application). It needs to be fixed, please. The "etcdctl" command errored out 3 times in a 17s span before working.

**Comment by chuckbutler** [comment]
This will make it into the docket if not the next release, the one directly after as papercuts are piling up. However, we will make this a priority fix.
