### ISSUE TITLE
Core and CDK issues on Joyent

### ISSUE THREAD

**Issue by joedborg** [juju-solutions/bundle-canonical-kubernetes#249]
I've been trying to deploy Core and CDK on a Joyent cluster.  The install hooks fail because apt isn't up to date:

```
root@dbe49d90-ba0d-ef45-dacd-e39bd2dba615:/var/lib/juju/agents/unit-etcd-0/charm# ./hooks/install 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-yaml is already the newest version (3.11-3build1).
The following additional packages will be installed:
  binutils build-essential cpp cpp-5 dpkg-dev fakeroot g++ g++-5 gcc gcc-5 libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl libasan2 libatomic1 libc-dev-bin
  libc6-dev libcc1-0 libcilkrts5 libdpkg-perl libexpat1-dev libfakeroot libfile-fcntllock-perl libgcc-5-dev libgomp1 libisl15 libitm1 liblsan0 libmpc3 libmpx0 libpython3-dev
  libpython3.5-dev libquadmath0 libstdc++-5-dev libtsan0 libubsan0 linux-libc-dev make manpages-dev python-pip-whl python3-wheel python3.5-dev
Suggested packages:
  binutils-doc cpp-doc gcc-5-locales debian-keyring g++-multilib g++-5-multilib gcc-5-doc libstdc++6-5-dbg gcc-multilib autoconf automake libtool flex bison gdb gcc-doc
  gcc-5-multilib libgcc1-dbg libgomp1-dbg libitm1-dbg libatomic1-dbg libasan2-dbg liblsan0-dbg libtsan0-dbg libubsan0-dbg libcilkrts5-dbg libmpx0-dbg libquadmath0-dbg glibc-doc
  libstdc++-5-doc make-doc python-setuptools-doc
The following NEW packages will be installed:
  binutils build-essential cpp cpp-5 dpkg-dev fakeroot g++ g++-5 gcc gcc-5 libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl libasan2 libatomic1 libc-dev-bin
  libc6-dev libcc1-0 libcilkrts5 libdpkg-perl libexpat1-dev libfakeroot libfile-fcntllock-perl libgcc-5-dev libgomp1 libisl15 libitm1 liblsan0 libmpc3 libmpx0 libpython3-dev
  libpython3.5-dev libquadmath0 libstdc++-5-dev libtsan0 libubsan0 linux-libc-dev make manpages-dev python-pip-whl python3-dev python3-pip python3-setuptools python3-wheel
  python3.5-dev
0 upgraded, 45 newly installed, 0 to remove and 2 not upgraded.
Need to get 837 kB/77.5 MB of archives.
After this operation, 201 MB of additional disk space will be used.
Err:1 http://security.ubuntu.com/ubuntu xenial-security/main amd64 linux-libc-dev amd64 4.4.0-71.92
  404  Not Found [IP: 91.189.88.149 80]
Err:1 http://security.ubuntu.com/ubuntu xenial-security/main amd64 linux-libc-dev amd64 4.4.0-71.92
  404  Not Found [IP: 91.189.88.149 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_4.4.0-71.92_amd64.deb  404  Not Found [IP: 91.189.88.149 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Traceback (most recent call last):
  File "./hooks/install", line 8, in <module>
    basic.bootstrap_charm_deps()
  File "lib/charms/layer/basic.py", line 54, in bootstrap_charm_deps
    'python3-dev',
  File "lib/charms/layer/basic.py", line 160, in apt_install
    check_call(cmd + packages, env=env)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-get', '--option=Dpkg::Options::=--force-confold', '--assume-yes', 'install', 'python3-pip', 'python3-setuptools', 'python3-yaml', 'python3-dev']' returned non-zero exit status 100

```
I can solve this by running `juju ssh [unit] sudo apt update -y` across all the units.  I assume the charms that make the bundle aren't running `apt update` because the "big data" bundles seem to work.

I've tried this via `juju deploy` and `conjure-up`.

**Comment by mbruzek** [comment]
Hi @joedborg thanks for the report. I thought the apt-layer should be handling a refresh as the first thing it does. If it is not doing that we should look into this problem. If you have a suggested fix please let us know, otherwise we will dig into then when we get a chance to breathe

**Comment by joedborg** [comment]
Hey @mbruzek, no worries at all!  Yes, I'd assumed the same.  I'm not really sure if it's a bundle or Joyent issue (seems to be a bit of both).  No rush whatsoever from my side :), I'll see if I can come up with a fix that doesn't affect the charms too much.

**Comment by tvansteenburgh** [comment]
AFAICT the etcd charm wasn't using the apt layer, which explains the original problem. In any case, the etcd charm now uses snaps, so this bug is no longer valid.
