### ISSUE TITLE
The v1.6.1 candidate failed to install on LXD ... then it worked!

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/bundle-canonical-kubernetes#250]
I was testing the latest 1.6.1 candidate today on LXD via conjure-up. The conjure-up screen indicated the "Application did not start successfully" in red which means the charms did not install correctly.

I checked the `juju status` and everything looks fine, so I went off investigating which charm failed (possible bug here that conjure-up does not tell us which charm failed). I found an ERROR in the kubernetes-worker charm log file. http://paste.ubuntu.com/24330227/

It looks to me like the snap failed to download (unexpected EOF), but when Juju retried it it worked. This confuses me.

```
2017-04-06 21:28:25 INFO install core 76.86 MB / 78.35 MB   98.10% 4.26 MB/s 0
2017-04-06 21:28:25 INFO install core 77.80 MB / 78.35 MB   99.30% 4.27 MB/s 0
2017-04-06 21:28:25 INFO install core 78.31 MB / 78.35 MB   99.96% 4.25 MB/s 0
2017-04-06 21:28:25 INFO install [Kerror: cannot perform the following tasks:
2017-04-06 21:28:25 INFO install - Download snap "core" (1577) from channel "stable" (unexpected EOF)
2017-04-06 21:28:25 INFO install 
2017-04-06 21:28:25 INFO install Traceback (most recent call last):
2017-04-06 21:28:25 INFO install   File "/var/lib/juju/agents/unit-kubernetes-worker-0/charm/hooks/install", line 19, in <module>
2017-04-06 21:28:25 INFO install     main()
2017-04-06 21:28:25 INFO install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
2017-04-06 21:28:25 INFO install     bus.dispatch()
2017-04-06 21:28:25 INFO install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
2017-04-06 21:28:25 INFO install     _invoke(other_handlers)
2017-04-06 21:28:25 INFO install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
2017-04-06 21:28:25 INFO install     handler.invoke()
2017-04-06 21:28:25 INFO install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
2017-04-06 21:28:25 INFO install     self._action(*args)
2017-04-06 21:28:25 INFO install   File "/var/lib/juju/agents/unit-kubernetes-worker-0/charm/reactive/kubernetes_worker.py", line 137, in install_snaps
2017-04-06 21:28:25 INFO install     snap.install('kubectl', channel=channel, classic=True)
2017-04-06 21:28:25 INFO install   File "lib/charms/layer/snap.py", line 44, in install
2017-04-06 21:28:25 INFO install     _install_store(snapname, **kw)
2017-04-06 21:28:25 INFO install   File "lib/charms/layer/snap.py", line 142, in _install_store
2017-04-06 21:28:25 INFO install     stderr=subprocess.STDOUT)
2017-04-06 21:28:25 INFO install   File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
2017-04-06 21:28:25 INFO install     **kwargs).stdout
2017-04-06 21:28:25 INFO install   File "/usr/lib/python3.5/subprocess.py", line 708, in run
2017-04-06 21:28:25 INFO install     output=stdout, stderr=stderr)
2017-04-06 21:28:25 INFO install subprocess.CalledProcessError: Command '['snap', 'install', '--classic', 'kubectl']' returned non-zero exit status 1
2017-04-06 21:28:25 ERROR juju.worker.uniter.operation runhook.go:107 hook "install" failed: exit status 1
2017-04-06 21:28:25 DEBUG juju.worker.uniter.operation executor.go:84 lock released
```
We should take a look at fixing this, if possible.

**Comment by marcoceppi** [comment]
iunexpected EOF seems to me the network connection dropped. juju
should auto retry the hook but we should have the snap layer retry
snap install failures regardless.

**Comment by johnsca** [comment]
The spell uses `juju-wait` to watch for the deployment to settle.  The current behavior of `juju-wait` is to fail immediately if it sees a hook error, which is not entirely unreasonable, but doesn't account for Juju's automatic hook retry.  I think that `juju-wait` should be modified to give an errored application a bit of time to allow for the auto-retry to kick in.

I also think that either snapd or the snap layer should handle this more gracefully, though, so that the hook doesn't error in the first place.

**Comment by mbruzek** [comment]
While working on a fix it was pointed out to me that is is really a snapd issue, and it should retry if it gets an error. Fixing this error at a snapd level makes the most sense for me.

I found a snapd bug about EOF that might be related, and added the log information I got here. https://bugs.launchpad.net/snapd/+bug/1677557

**Comment by mbruzek** [comment]
My proposed fix landed in layer-snap here: https://github.com/stub42/layer-snap/pull/8 

We should rebuild the kubernetes charms and verify snap installs continue to work.
