### ISSUE TITLE
install with juju resources -  Download snap "core" (1577) from channel "stable" timeout

### ISSUE THREAD

**Issue by larrymi** [juju-solutions/bundle-canonical-kubernetes#256]
This is for doing an install where firewall is blocking some the access to the snap store so using juju resources to upload the resources to the controller. However, this is still failing because of the core snap.

This is juju status:

$ juju status
Model              Controller    Cloud/Region  Version
k8s-maas-resource  testlxdimage  larry         2.2-beta2

App                    Version  Status   Scale  Charm                  Store       Rev  OS      Notes
easyrsa                3.0.1    active       1  easyrsa                jujucharms    8  ubuntu  
etcd                            error        3  etcd                   jujucharms   29  ubuntu  
flannel                         waiting      0  flannel                jujucharms   13  ubuntu  
kubeapi-load-balancer  1.10.0   active       1  kubeapi-load-balancer  jujucharms   10  ubuntu  exposed
kubernetes-master               error        1  kubernetes-master      jujucharms   17  ubuntu  
kubernetes-worker               error        3  kubernetes-worker      jujucharms   21  ubuntu  exposed

Unit                      Workload  Agent  Machine  Public address  Ports  Message
easyrsa/0*                active    idle   0        10.245.21.13           Certificate Authority connected.
etcd/0                    error     idle   1        10.245.21.14           hook failed: "install"
etcd/1*                   error     idle   2        10.245.21.15           hook failed: "install"
etcd/2                    error     idle   3        10.245.21.16           hook failed: "install"
kubeapi-load-balancer/0*  active    idle   4        10.245.21.18           NGINX is ready
kubernetes-master/0*      error     idle   5        10.245.21.19           hook failed: "install"
kubernetes-worker/0       error     idle   6        10.245.21.20           hook failed: "install"
kubernetes-worker/1*      error     idle   7        10.245.21.17           hook failed: "install"
kubernetes-worker/2       error     idle   8        10.245.21.21           hook failed: "install"

Machine  State    DNS           Inst id  Series  AZ          Message
0        started  10.245.21.13  6ctrbt   xenial  Production  Deployed
1        started  10.245.21.14  khccbr   xenial  default     Deployed
2        started  10.245.21.15  4a68ky   xenial  Production  Deployed
3        started  10.245.21.16  kyxc67   xenial  Production  Deployed
4        started  10.245.21.18  e4yrfn   xenial  default     Deployed
5        started  10.245.21.19  hegqeb   xenial  Production  Deployed
6        started  10.245.21.20  7qp3fq   xenial  Production  Deployed
7        started  10.245.21.17  bc37gs   xenial  default     Deployed
8        started  10.245.21.21  88kcrd   xenial  Production  Deployed

Relation           Provides               Consumes               Type
certificates       easyrsa                etcd                   regular
certificates       easyrsa                kubeapi-load-balancer  regular
certificates       easyrsa                kubernetes-master      regular
certificates       easyrsa                kubernetes-worker      regular
cluster            etcd                   etcd                   peer
etcd               etcd                   flannel                regular
etcd               etcd                   kubernetes-master      regular
cni                flannel                kubernetes-master      regular
cni                flannel                kubernetes-worker      regular
loadbalancer       kubeapi-load-balancer  kubernetes-master      regular
kube-api-endpoint  kubeapi-load-balancer  kubernetes-worker      regular
cni                kubernetes-master      flannel                subordinate
kube-control       kubernetes-master      kubernetes-worker      regular
cni                kubernetes-worker      flannel                subordinate

And this is from attached unit file:
2017-04-10 21:59:37 DEBUG worker.uniter.jujuc server.go:178 hook context id "kubernetes-master/0-install-2962080428732376357"; dir "/var/lib/juju/agents/unit-kubernetes-master-0/charm"
2017-04-10 21:59:38 DEBUG worker.uniter.jujuc server.go:178 hook context id "kubernetes-master/0-install-2962080428732376357"; dir "/var/lib/juju/agents/unit-kubernetes-master-0/charm"
2017-04-10 21:59:38 DEBUG httpbakery client.go:244 client do GET https://10.245.30.93:17070/model/249a5455-8c40-423a-8c2e-e7be47d16212/units/unit-kubernetes-master-0/resources/kubectl {
2017-04-10 21:59:38 DEBUG httpbakery client.go:246 } -> error <nil>
2017-04-10 21:59:39 DEBUG worker.uniter.jujuc server.go:178 hook context id "kubernetes-master/0-install-2962080428732376357"; dir "/var/lib/juju/agents/unit-kubernetes-master-0/charm"
2017-04-10 21:59:39 INFO juju-log Installing /var/lib/juju/agents/unit-kubernetes-master-0/resources/kubectl/kubectl.snap from local resource
[\] Download snap "core" (1577) from channel "stable"
[\] Download snap "core" (1577) from channel "stable"
[\] Download snap "core" (1577) from channel "stable"
[\] Download snap "core" (1577) from channel "stable"
[\] Download snap "core" (1577) from channel "stable"
[\] Download snap "core" (1577) from channel "stable"
[-] Download snap "core" (1577) from channel "stable"
[-] Download snap "core" (1577) from channel "stable"
error: cannot perform the following tasks:
2017-04-10 22:00:40 INFO install - Download snap "core" (1577) from channel "stable" (Get https://public.apps.ubuntu.com/anon/download-snap/99T7MUlRhtI3U0QFgl5mXXESAiSwt776_1577.snap: dial tcp 162.213.33.92:443: i/o timeout)
2017-04-10 22:00:40 INFO install Traceback (most recent call last):
2017-04-10 22:00:40 INFO install   File "/var/lib/juju/agents/unit-kubernetes-master-0/charm/hooks/install", line 19, in <module>
2017-04-10 22:00:40 INFO install     main()
2017-04-10 22:00:40 INFO install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
2017-04-10 22:00:40 INFO install     bus.dispatch()
2017-04-10 22:00:40 INFO install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
2017-04-10 22:00:40 INFO install     _invoke(other_handlers)
2017-04-10 22:00:40 INFO install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
2017-04-10 22:00:40 INFO install     handler.invoke()
2017-04-10 22:00:40 INFO install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
2017-04-10 22:00:40 INFO install     self._action(*args)
2017-04-10 22:00:40 INFO install   File "/var/lib/juju/agents/unit-kubernetes-master-0/charm/reactive/kubernetes_master.py", line 156, in channel_changed
2017-04-10 22:00:40 INFO install     install_snaps()
2017-04-10 22:00:40 INFO install   File "/var/lib/juju/agents/unit-kubernetes-master-0/charm/reactive/kubernetes_master.py", line 141, in install_snaps
2017-04-10 22:00:40 INFO install     snap.install('kubectl', channel=channel, classic=True)
2017-04-10 22:00:40 INFO install   File "lib/charms/layer/snap.py", line 47, in install
2017-04-10 22:00:40 INFO install     _install_local(res_path, **kw)
2017-04-10 22:00:40 INFO install   File "lib/charms/layer/snap.py", line 130, in _install_local
2017-04-10 22:00:40 INFO install     subprocess.check_call(cmd, universal_newlines=True)
2017-04-10 22:00:40 INFO install   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
2017-04-10 22:00:40 INFO install     raise CalledProcessError(retcode, cmd)
2017-04-10 22:00:40 INFO install subprocess.CalledProcessError: Command '['snap', 'install', '--classic', '--dangerous', '/var/lib/juju/agents/unit-kubernetes-master-0/resources/kubectl/kubectl.snap']' returned non-zero exit status 1

Here are some unit log files for failed units:

[logs.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/911642/logs.tar.gz)

**Comment by mbruzek** [comment]
Looking at the logs that @larrymi provided, it seems we don't have the core snap when installing off-line. This is something we will have to think about how to resolve.

**Comment by arosales** [comment]
As a debug measure I suggested to have @larrymi download the core snap from https://uappexplorer.com/app/core.canonical and then juju scp the core snap. Juju-2 should automatically retry the hook[0].

If this does work we'll need to make a resource for the core snap when installing in snap-mode.

[0] https://jujucharms.com/docs/2.1/models-config#retrying-failed-hooks

-thanks,
Antonio

**Comment by larrymi** [comment]
@arosales I downloaded the core snap, scp'ed to the units and installed with snap install core.snap --dangerous followed followed by juju resolved <unit> for the failed units. That got me past the install errors and everything else seem to work.
![screenshot from 2017-04-11 11-25-41](https://cloud.githubusercontent.com/assets/13599808/24919920/e0a647de-1eaa-11e7-9cb3-563fd4fa81f8.png)

**Comment by chuckbutler** [comment]
This affects k8s deployments, but feels to me like this is a bug best targeted at snappy. We're recommending users circumvent updates and no longer receive core snap updates which include security fixes. There's a good chance this workaround of installing offline could lead to introducing a security vulnerability.
