### ISSUE TITLE
hook failure if gpu worker labels itself before master is up

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/bundle-canonical-kubernetes#303]
I pre-deployed workers because i wanted them on GPU hardware.  Then I deployed the can-kub bundle.  The workers got stuck in a cni hook loop as described below:

```
$ juju deploy kubernetes-worker --constraints instance-type=<gpu>
## wait for giggles
$ juju deploy canonical-kubernets
```
The bundle will re-use the workers.  Before the master is ready, the workers run `cni-relation-changed`:

```
unit-kubernetes-worker-0: 16:41:45 INFO unit.kubernetes-worker/0.cni-relation-changed Fri Jun  9 16:41:45 2017
unit-kubernetes-worker-0: 16:41:45 INFO unit.kubernetes-worker/0.cni-relation-changed +-----------------------------------------------------------------------------+
unit-kubernetes-worker-0: 16:41:45 INFO unit.kubernetes-worker/0.cni-relation-changed | NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
unit-kubernetes-worker-0: 16:41:45 INFO unit.kubernetes-worker/0.cni-relation-changed |-------------------------------+----------------------+----------------------+
unit-kubernetes-worker-0: 16:41:45 INFO unit.kubernetes-worker/0.cni-relation-changed | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
unit-kubernetes-worker-0: 16:41:45 INFO unit.kubernetes-worker/0.cni-relation-changed | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
unit-kubernetes-worker-0: 16:41:45 INFO unit.kubernetes-worker/0.cni-relation-changed |===============================+======================+======================|
unit-kubernetes-worker-0: 16:41:46 INFO unit.kubernetes-worker/0.cni-relation-changed |   0  Tesla K80           Off  | 98D0:00:00.0     Off |                    0 |
unit-kubernetes-worker-0: 16:41:46 INFO unit.kubernetes-worker/0.cni-relation-changed | N/A   35C    P0    73W / 149W |      0MiB / 11439MiB |     85%      Default |
unit-kubernetes-worker-0: 16:41:46 INFO unit.kubernetes-worker/0.cni-relation-changed +-------------------------------+----------------------+----------------------+
unit-kubernetes-worker-0: 16:41:46 INFO unit.kubernetes-worker/0.cni-relation-changed
unit-kubernetes-worker-0: 16:41:46 INFO unit.kubernetes-worker/0.cni-relation-changed +-----------------------------------------------------------------------------+
unit-kubernetes-worker-0: 16:41:46 INFO unit.kubernetes-worker/0.cni-relation-changed | Processes:                                                       GPU Memory |
unit-kubernetes-worker-0: 16:41:46 INFO unit.kubernetes-worker/0.cni-relation-changed |  GPU       PID  Type  Process name                               Usage      |
unit-kubernetes-worker-0: 16:41:46 INFO unit.kubernetes-worker/0.cni-relation-changed |=============================================================================|
unit-kubernetes-worker-0: 16:41:46 INFO unit.kubernetes-worker/0.cni-relation-changed |  No running processes found                                                 |
unit-kubernetes-worker-0: 16:41:46 INFO unit.kubernetes-worker/0.cni-relation-changed +-----------------------------------------------------------------------------+
unit-kubernetes-worker-0: 16:41:47 INFO unit.kubernetes-worker/0.juju-log cni:12: Adding --feature-gates=Accelerators=true to kubelet
unit-kubernetes-worker-0: 16:41:47 INFO unit.kubernetes-worker/0.cni-relation-changed The connection to the server 192.168.0.11:443 was refused - did you specify the right host or port?
unit-kubernetes-worker-0: 16:41:47 INFO unit.kubernetes-worker/0.cni-relation-changed Traceback (most recent call last):
unit-kubernetes-worker-0: 16:41:47 INFO unit.kubernetes-worker/0.cni-relation-changed   File "/var/lib/juju/agents/unit-kubernetes-worker-0/charm/hooks/cni-relation-changed", line 19, in <module>
unit-kubernetes-worker-0: 16:41:47 INFO unit.kubernetes-worker/0.cni-relation-changed     main()
unit-kubernetes-worker-0: 16:41:47 INFO unit.kubernetes-worker/0.cni-relation-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
unit-kubernetes-worker-0: 16:41:47 INFO unit.kubernetes-worker/0.cni-relation-changed     bus.dispatch()
unit-kubernetes-worker-0: 16:41:47 INFO unit.kubernetes-worker/0.cni-relation-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 423, in dispatch
unit-kubernetes-worker-0: 16:41:47 INFO unit.kubernetes-worker/0.cni-relation-changed     _invoke(other_handlers)
unit-kubernetes-worker-0: 16:41:47 INFO unit.kubernetes-worker/0.cni-relation-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 406, in _invoke
unit-kubernetes-worker-0: 16:41:47 INFO unit.kubernetes-worker/0.cni-relation-changed     handler.invoke()
unit-kubernetes-worker-0: 16:41:47 INFO unit.kubernetes-worker/0.cni-relation-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 280, in invoke
unit-kubernetes-worker-0: 16:41:47 INFO unit.kubernetes-worker/0.cni-relation-changed     self._action(*args)
unit-kubernetes-worker-0: 16:41:47 INFO unit.kubernetes-worker/0.cni-relation-changed   File "/var/lib/juju/agents/unit-kubernetes-worker-0/charm/reactive/kubernetes_worker.py", line 712, in enable_gpu
unit-kubernetes-worker-0: 16:41:47 INFO unit.kubernetes-worker/0.cni-relation-changed     _apply_node_label('gpu=true', overwrite=True)
unit-kubernetes-worker-0: 16:41:47 INFO unit.kubernetes-worker/0.cni-relation-changed   File "/var/lib/juju/agents/unit-kubernetes-worker-0/charm/reactive/kubernetes_worker.py", line 804, in _apply_node_label
unit-kubernetes-worker-0: 16:41:47 INFO unit.kubernetes-worker/0.cni-relation-changed     check_call(split(cmd))
unit-kubernetes-worker-0: 16:41:47 INFO unit.kubernetes-worker/0.cni-relation-changed   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
unit-kubernetes-worker-0: 16:41:47 INFO unit.kubernetes-worker/0.cni-relation-changed     raise CalledProcessError(retcode, cmd)
unit-kubernetes-worker-0: 16:41:47 INFO unit.kubernetes-worker/0.cni-relation-changed subprocess.CalledProcessError: Command '['kubectl', '--kubeconfig=/root/cdk/kubeconfig', 'label', 'node', 'machine-0', 'gpu=true', '--overwrite']' returned non-zero exit status 1
unit-kubernetes-worker-0: 16:41:47 ERROR juju.worker.uniter.operation hook "cni-relation-changed" failed: exit status 1
```

I'm presuming this is because the master isn't up yet.  Once the master eventually gets to `Kubernetes master running`, the next worker hook retry resolves itself and everything settles to `active`.

The `hook failure` in status is spooky.  Is there some state that you can react to so the cni hook doesn't try to label the node until the master is ready?

**Comment by chuckbutler** [comment]
Great catch, this could easily be prevented by adding the kube-api-endpoint state guard. It won't be 100% effective but would reduce the chances of this greatly, and we should also generalize the kubernetes operations to be retry friendly.

Once RBAC lands, we're going to encounter scenarios where the master services are restarting more often than they have in the past.
