### ISSUE TITLE
flannel goes into error state when etcd isn't ready

### ISSUE THREAD

**Issue by battlemidget** [juju-solutions/bundle-canonical-kubernetes#312]
https://pastebin.canonical.com/191409/

```
017-06-20 14:50:39 INFO juju-log etcd:2: Invoking reactive handler: reactive/flannel.py:109:configure_network
2017-06-20 14:50:39 INFO etcd-relation-changed Error:  client: etcd cluster is unavailable or misconfigured
2017-06-20 14:50:39 INFO etcd-relation-changed error #0: dial tcp 10.245.12.91:2379: getsockopt: connection refused
2017-06-20 14:50:39 INFO etcd-relation-changed error #1: dial tcp 10.245.12.89:2379: getsockopt: connection refused
2017-06-20 14:50:39 INFO etcd-relation-changed 
2017-06-20 14:50:39 INFO etcd-relation-changed Traceback (most recent call last):
2017-06-20 14:50:39 INFO etcd-relation-changed   File "/var/lib/juju/agents/unit-flannel-0/charm/hooks/etcd-relation-changed", line 19, in <module>
2017-06-20 14:50:39 INFO etcd-relation-changed     main()
2017-06-20 14:50:39 INFO etcd-relation-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
2017-06-20 14:50:39 INFO etcd-relation-changed     bus.dispatch()
2017-06-20 14:50:39 INFO etcd-relation-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 423, in dispatch
2017-06-20 14:50:39 INFO etcd-relation-changed     _invoke(other_handlers)
2017-06-20 14:50:39 INFO etcd-relation-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 406, in _invoke
2017-06-20 14:50:39 INFO etcd-relation-changed     handler.invoke()
2017-06-20 14:50:39 INFO etcd-relation-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 280, in invoke
2017-06-20 14:50:39 INFO etcd-relation-changed     self._action(*args)
2017-06-20 14:50:39 INFO etcd-relation-changed   File "/var/lib/juju/agents/unit-flannel-0/charm/reactive/flannel.py", line 126, in configure_network
2017-06-20 14:50:39 INFO etcd-relation-changed     check_call(split(cmd))
2017-06-20 14:50:39 INFO etcd-relation-changed   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
2017-06-20 14:50:39 INFO etcd-relation-changed     raise CalledProcessError(retcode, cmd)
2017-06-20 14:50:39 INFO etcd-relation-changed subprocess.CalledProcessError: Command '['etcdctl', '--endpoint', 'https://10.245.12.89:2379,https://10.245.12.91:2379', '--cert-file', '/etc/ssl/flannel/client-cert.pem', '--key-file', '/etc/ssl/flannel/client-key.pem', '--ca-file', '/etc/ssl/flannel/client-ca.pem', 'set', '/coreos.com/network/config', '{"Network": "10.1.0.0/16", "Backend": {"Type": "vxlan"}}']' returned non-zero exit status 2
2017-06-20 14:50:39 ERROR juju.worker.uniter.operation runhook.go:107 hook "etcd-relation-changed" failed: exit status 1
```

This eventually fixes itself, however, if using things like `juju wait` the damage has been done and `conjure-up` will fail to continue on.

**Comment by canonical-cgregan** [comment]
This is using Conjure up 2.2.1 and Canonical-k8s #38
