### ISSUE TITLE
Ceph PV action fails if disks are in GB and not MB

### ISSUE THREAD

**Issue by SaMnCo** [juju-solutions/bundle-canonical-kubernetes#347]
With a juju 2.2.1 / Kubernetes 1.7.0 / Ceph bundle deployed from scratch on MAAS: 

<pre><code>
$ juju run-action kubernetes-master/0 create-rbd-pv name=test size=4096
Action queued with id: 5d9355ca-532e-4904-83d1-39ff4ca4394a

$ juju show-action-output 5d9355ca-532e-4904-83d1-39ff4ca4394a
message: exit status 1
status: failed
timing:
  completed: 2017-07-12 09:00:22 +0000 UTC
  enqueued: 2017-07-12 09:00:19 +0000 UTC
  started: 2017-07-12 09:00:21 +0000 UTC
</code></pre>

The log from the action is

<pre><code>
2017-07-12 09:06:36 INFO create-rbd-pv Invoking ['ceph', 'health']
2017-07-12 09:06:36 INFO create-rbd-pv Invoking ['ceph', 'df']
2017-07-12 09:06:36 INFO create-rbd-pv Traceback (most recent call last):
2017-07-12 09:06:36 INFO create-rbd-pv   File "/var/lib/juju/agents/unit-kubernetes-master-0/charm/actions/create-rbd-pv", line 300, in <module>
2017-07-12 09:06:36 INFO create-rbd-pv     main()
2017-07-12 09:06:36 INFO create-rbd-pv   File "/var/lib/juju/agents/unit-kubernetes-master-0/charm/actions/create-rbd-pv", line 59, in main
2017-07-12 09:06:36 INFO create-rbd-pv     if not validate_space(context['RBD_SIZE']):
2017-07-12 09:06:36 INFO create-rbd-pv   File "/var/lib/juju/agents/unit-kubernetes-master-0/charm/actions/create-rbd-pv", line 246, in validate_space
2017-07-12 09:06:36 INFO create-rbd-pv     available_space = get_available_space()
2017-07-12 09:06:36 INFO create-rbd-pv   File "/var/lib/juju/agents/unit-kubernetes-master-0/charm/actions/create-rbd-pv", line 189, in get_available_space
2017-07-12 09:06:36 INFO create-rbd-pv     return int(M)
2017-07-12 09:06:36 INFO create-rbd-pv ValueError: invalid literal for int() with base 10: '445G'
</code></pre>

Looking at the code in the action, it seems that it only expects ```ceph df``` to return M (Megabytes). However, 

<pre><code>
$ ceph df
GLOBAL:
    SIZE      AVAIL     RAW USED     %RAW USED 
    1337G     1337G         103M             0 
POOLS:
    NAME     ID     USED     %USED     MAX AVAIL     OBJECTS 
    rbd      0        16         0          445G           3 
</code></pre>

This is with 3x 500GB drives. I would expect that with like 4TB drives, the answer is maybe with T, or even P. 

Rewriting the create-rbd-vol action to replace 'G' by '000' then makes the action succeed:

<pre><code>
2017-07-12 09:18:28 INFO create-rbd-pv meta-data=/dev/rbd1              isize=512    agcount=9, agsize=130048 blks
2017-07-12 09:18:28 INFO create-rbd-pv          =                       sectsz=512   attr=2, projid32bit=1
2017-07-12 09:18:28 INFO create-rbd-pv          =                       crc=1        finobt=1, sparse=0
2017-07-12 09:18:28 INFO create-rbd-pv data     =                       bsize=4096   blocks=1048576, imaxpct=25
2017-07-12 09:18:28 INFO create-rbd-pv          =                       sunit=1024   swidth=1024 blks
2017-07-12 09:18:28 INFO create-rbd-pv naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
2017-07-12 09:18:28 INFO create-rbd-pv log      =internal log           bsize=4096   blocks=2560, version=2
2017-07-12 09:18:28 INFO create-rbd-pv          =                       sectsz=512   sunit=8 blks, lazy-count=1
2017-07-12 09:18:28 INFO create-rbd-pv realtime =none                   extsz=4096   blocks=0, rtextents=0
2017-07-12 09:18:28 INFO juju-log Writing file /tmp/tmp1i_v080b/pv.yaml root:root 444
2017-07-12 09:18:28 INFO create-rbd-pv persistentvolume "test" created
2017-07-12 09:18:28 INFO create-rbd-pv Invoking ['ceph', 'health']
2017-07-12 09:18:28 INFO create-rbd-pv Invoking ['ceph', 'df']
2017-07-12 09:18:28 INFO create-rbd-pv Invoking ['rbd', 'list']
2017-07-12 09:18:28 INFO create-rbd-pv Invoking ['rbd', 'create', '--size', '4096', '--image-feature', 'layering', 'test']
2017-07-12 09:18:28 INFO create-rbd-pv Invoking ['rbd', 'list']
2017-07-12 09:18:28 INFO create-rbd-pv Invoking ['rbd', 'map', 'test']
2017-07-12 09:18:28 INFO create-rbd-pv Invoking ['mkfs.xfs', b'/dev/rbd1']
2017-07-12 09:18:28 INFO create-rbd-pv Invoking ['rbd', 'unmap', 'test']
2017-07-12 09:18:28 INFO create-rbd-pv Invoking ['kubectl', 'create', '-f', '/tmp/tmp1i_v080b/pv.yaml']
</code></pre>

**Comment by tvansteenburgh** [comment]
@SaMnCo Thanks for the detailed bug report!

**Comment by tvansteenburgh** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/49394
