### ISSUE TITLE
Error in Calico Policy Controller logs: Unhandled exception killed NetworkPolicy manager, Unhandled exception killed Namespace manager

### ISSUE THREAD

**Issue by tvansteenburgh** [juju-solutions/bundle-canonical-kubernetes#400]
via @eric-sonchaiwanich

> In another CDK/canal environment, I’ve observed one instance where the Calico Policy Controller had 1.8GB of logs with repeating errors.  In this cluster, the master and worker nodes were de-provisioned and re-provisioned.

```
...
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2017-08-28 19:36:35,989 9 INFO Restarting watch on resource: Pod
2017-08-28 19:36:36,309 9 INFO Syncing 'Namespace' objects
2017-08-28 19:36:36,321 9 ERROR Unhandled exception killed Namespace manager
Traceback (most recent call last):
  File "<string>", line 324, in _manage_resource
  File "<string>", line 441, in _sync_resources
  File "site-packages/requests/models.py", line 866, in json
  File "site-packages/simplejson/__init__.py", line 516, in loads
  File "site-packages/simplejson/decoder.py", line 374, in decode
  File "site-packages/simplejson/decoder.py", line 404, in raw_decode
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2017-08-28 19:36:36,322 9 INFO Restarting watch on resource: Namespace
2017-08-28 19:36:36,986 9 INFO Syncing 'NetworkPolicy' objects
2017-08-28 19:36:36,990 9 INFO Syncing 'Pod' objects
2017-08-28 19:36:36,998 9 ERROR Unhandled exception killed NetworkPolicy manager
Traceback (most recent call last):
  File "<string>", line 324, in _manage_resource
  File "<string>", line 441, in _sync_resources
  File "site-packages/requests/models.py", line 866, in json
  File "site-packages/simplejson/__init__.py", line 516, in loads
  File "site-packages/simplejson/decoder.py", line 374, in decode
  File "site-packages/simplejson/decoder.py", line 404, in raw_decode
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2017-08-28 19:36:36,998 9 INFO Restarting watch on resource: NetworkPolicy
2017-08-28 19:36:37,004 9 ERROR Unhandled exception killed Pod manager
Traceback (most recent call last):
  File "<string>", line 324, in _manage_resource
  File "<string>", line 441, in _sync_resources
  File "site-packages/requests/models.py", line 866, in json
  File "site-packages/simplejson/__init__.py", line 516, in loads
  File "site-packages/simplejson/decoder.py", line 374, in decode
  File "site-packages/simplejson/decoder.py", line 404, in raw_decode
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2017-08-28 19:36:37,004 9 INFO Restarting watch on resource: Pod
2017-08-28 19:36:37,323 9 INFO Syncing 'Namespace' objects
2017-08-28 19:36:37,337 9 ERROR Unhandled exception killed Namespace manager
Traceback (most recent call last):
  File "<string>", line 324, in _manage_resource
  File "<string>", line 441, in _sync_resources
  File "site-packages/requests/models.py", line 866, in json
  File "site-packages/simplejson/__init__.py", line 516, in loads
  File "site-packages/simplejson/decoder.py", line 374, in decode
  File "site-packages/simplejson/decoder.py", line 404, in raw_decode
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2017-08-28 19:36:37,337 9 INFO Restarting watch on resource: Namespace
...
```

> Note that the canal unit numbers were also much higher than expected:

```
$ juju status
Model       Controller           Cloud/Region   Version  SLA
fog-dev-dr  noble-us-east-1-k8s  aws/us-east-1  2.2.2    unsupported

App                    Version      Status  Scale  Charm                  Store       Rev  OS      Notes
canal                  0.7.0/1.3.0  active      8  canal                  jujucharms    8  ubuntu  
easyrsa                3.0.1        active      1  easyrsa                jujucharms   12  ubuntu  
etcd                   2.3.8        active      3  etcd                   jujucharms   40  ubuntu  
kubeapi-load-balancer  1.10.3       active      1  kubeapi-load-balancer  jujucharms   16  ubuntu  exposed
kubernetes-master      1.7.0        active      2  kubernetes-master      jujucharms   35  ubuntu  exposed
kubernetes-worker      1.7.0        active      6  kubernetes-worker      jujucharms   40  ubuntu  exposed

Unit                      Workload  Agent  Machine  Public address  Ports           Message
easyrsa/0*                active    idle   0        10.100.30.184                   Certificate Authority connected.
etcd/0*                   active    idle   3        10.100.30.216   2379/tcp        Healthy with 3 known peers
etcd/1                    active    idle   1        10.100.31.41    2379/tcp        Healthy with 3 known peers
etcd/2                    active    idle   2        10.100.32.60    2379/tcp        Healthy with 3 known peers
kubeapi-load-balancer/0*  active    idle   13       10.100.30.208   443/tcp         Loadbalancer ready.
kubernetes-master/2       active    idle   17       10.100.30.138   6443/tcp        Kubernetes master running.
  canal/38                active    idle            10.100.30.138                   Flannel subnet 10.1.106.1/24
kubernetes-master/3*      active    idle   16       10.100.31.250   6443/tcp        Kubernetes master running.
  canal/37                active    idle            10.100.31.250                   Flannel subnet 10.1.18.1/24
kubernetes-worker/9*      active    idle   18       10.100.30.81    80/tcp,443/tcp  Kubernetes worker running.
  canal/36*               active    idle            10.100.30.81                    Flannel subnet 10.1.13.1/24
kubernetes-worker/10      active    idle   19       10.100.30.149   80/tcp,443/tcp  Kubernetes worker running.
  canal/39                active    idle            10.100.30.149                   Flannel subnet 10.1.73.1/24
kubernetes-worker/11      active    idle   20       10.100.30.229   80/tcp,443/tcp  Kubernetes worker running.
  canal/40                active    idle            10.100.30.229                   Flannel subnet 10.1.45.1/24
kubernetes-worker/12      active    idle   21       10.100.31.183   80/tcp,443/tcp  Kubernetes worker running.
  canal/41                active    idle            10.100.31.183                   Flannel subnet 10.1.79.1/24
kubernetes-worker/13      active    idle   22       10.100.31.5     80/tcp,443/tcp  Kubernetes worker running.
  canal/42                active    idle            10.100.31.5                     Flannel subnet 10.1.28.1/24
kubernetes-worker/14      active    idle   23       10.100.31.214   80/tcp,443/tcp  Kubernetes worker running.
  canal/43                active    idle            10.100.31.214                   Flannel subnet 10.1.76.1/24

Machine  State    DNS            Inst id              Series  AZ          Message
0        started  10.100.30.184  i-0174664bb040449c4  xenial  us-east-1a  running
1        started  10.100.31.41   i-015d32d27e9a721a3  xenial  us-east-1b  running
2        started  10.100.32.60   i-0667dc6bb144021e2  xenial  us-east-1c  running
3        started  10.100.30.216  i-0591754b312658714  xenial  us-east-1a  running
13       started  10.100.30.208  i-0413e1158cfed01d8  xenial  us-east-1a  running
16       started  10.100.31.250  i-0a25be94014124d7e  xenial  us-east-1b  running
17       started  10.100.30.138  i-05536a550ea90b1f7  xenial  us-east-1a  running
18       started  10.100.30.81   i-02925b9c3b2a389ce  xenial  us-east-1a  running
19       started  10.100.30.149  i-0dd6bc1921e3c3301  xenial  us-east-1a  running
20       started  10.100.30.229  i-03b6039f27a2812a9  xenial  us-east-1a  running
21       started  10.100.31.183  i-03c9c95d1a553ebf8  xenial  us-east-1b  running
22       started  10.100.31.5    i-02f420324f0c21d6c  xenial  us-east-1b  running
23       started  10.100.31.214  i-07ff4b59033a12abe  xenial  us-east-1b  running

Relation           Provides               Consumes               Type
db                 canal                  etcd                   regular
cni                canal                  kubernetes-master      regular
cni                canal                  kubernetes-worker      regular
certificates       easyrsa                etcd                   regular
certificates       easyrsa                kubeapi-load-balancer  regular
certificates       easyrsa                kubernetes-master      regular
certificates       easyrsa                kubernetes-worker      regular
cluster            etcd                   etcd                   peer
etcd               etcd                   kubernetes-master      regular
loadbalancer       kubeapi-load-balancer  kubernetes-master      regular
kube-api-endpoint  kubeapi-load-balancer  kubernetes-worker      regular
cni                kubernetes-master      canal                  subordinate
kube-control       kubernetes-master      kubernetes-worker      regular
cni                kubernetes-worker      canal                  subordinate
```

> **Workaround: The calico-policy manager service does not show errors after re-creating the pod (scaling the calico-policy-controller deployment to 0, then back up to 1).**

**Comment by Cynerva** [comment]
I'm not able to reproduce this issue. I'm hopeful that maybe we picked up a calico bug fix with this PR: https://github.com/juju-solutions/layer-canal/pull/4/files

Here's what I tried:
1. Recreated (remove-unit + add-unit) kubernetes-master unit
2. Recreated kubernetes-worker unit that did _not_ host the calico-policy-controller pod.
3. Recreated kubernetes-worker unit that _did_ host the calico-policy-controller pod.
4. Recreated all units of kubernetes-worker together.

At each step along the way, I checked the calico-policy-controller logs and didn't see a problem. I don't think there's much we can do right now except keep an eye out for it happening again.
