### ISSUE TITLE
CUDA doesn't work

### ISSUE THREAD

**Issue by rongou** [juju-solutions/bundle-canonical-kubernetes#430]
The current bundle doesn't seem to work out of the box for CUDA jobs (e.g. tensorflow). Or maybe I'm missing something obvious. :)

Steps to reproduce:
- Modify `kubernetes-worker` slightly by adding a constraint `instance-type=p2.xlarge` (for aws).
- Deploy to aws and wait for the cluster to start up.
- Launch a tensorflow job that tries to use the GPU.

Here is my yaml file:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: tensorflow-gpu
  labels:
    name: tensorflow-gpu
spec:
  template:
    metadata:
      labels:
        name: tensorflow-gpu
    spec:
      containers:
      - name: tensorflow-gpu
        image: gcr.io/tensorflow/tensorflow:latest-gpu
        command: [ "python" ]
        args: ["-c", "import tensorflow"]
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            alpha.kubernetes.io/nvidia-gpu: 1
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - mountPath: /usr/local/nvidia/bin
          name: bin
        - mountPath: /usr/lib/nvidia
          name: lib
      volumes:
        - name: bin
          hostPath:
            path: /usr/lib/nvidia-384/bin
        - name: lib
          hostPath:
            path: /usr/lib/nvidia-384
      restartPolicy: Never
```
I'm getting this from the pod:
```console
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```
After ssh'ing into the worker node and put nvidia-docker 2.0 on it (after upgrading to the latest docker-ce), it started working even without the volume mounts.

Is CUDA supposed to be working? Are you open to switch to nvidia-docker 2.0? I can try to put together a PR if that seems like a good idea. Thanks!

**Comment by rongou** [comment]
Hmm, never mind, I figured this out. For posterity, this is what worked:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: tensorflow-gpu
  labels:
    name: tensorflow-gpu
spec:
  template:
    metadata:
      labels:
        name: tensorflow-gpu
    spec:
      containers:
      - name: tensorflow-gpu
        image: gcr.io/tensorflow/tensorflow:latest-gpu
        command: [ "python" ]
        args: [
          "-c",
          "import tensorflow as tf; hello = tf.constant('Hello, TensorFlow!'); sess = tf.Session(); print(sess.run(hello))"
        ]
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            alpha.kubernetes.io/nvidia-gpu: 1
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - mountPath: /usr/local/nvidia/lib
          name: lib
        - mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
          name: libcuda-so-1
      volumes:
        - name: lib
          hostPath:
            path: /usr/lib/nvidia-384
        - name: libcuda-so-1
          hostPath:
            path: /usr/lib/x86_64-linux-gnu/libcuda.so.1
      restartPolicy: Never
```

**Comment by marcoceppi** [comment]
Thanks for the report and update. I'd like to take this opportunity to capture common issues, mind if I use this and update [our docs](https://kubernetes.io/docs/getting-started-guides/ubuntu/)?

**Comment by rongou** [comment]
Sure!
