### ISSUE TITLE
cuda install raise an unauthenticated packages error !

### ISSUE THREAD

**Issue by yaumeg** [juju-solutions/bundle-canonical-kubernetes#496]
Hi,
I have a MAAS + juju setup, was working like a charm, until today. Same bundle, same hardware, exact same context, but all my workers crash during setup when installing cuda, because of "unauthenticated packages" errors. If if force install-cuda to false in my bundle, my k8s deployment end with success. What is going on ?

Here is the log:

```unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 340, in _invoke
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install     handler.invoke()
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 242, in invoke
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install     subprocess.check_call([self._filepath, '--invoke', self._test_output], env=os.environ)
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install     raise CalledProcessError(retcode, cmd)
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install subprocess.CalledProcessError: Command '['/var/lib/juju/agents/unit-kubernetes-worker-0/charm/reactive/cuda.sh', '--invoke', b'install_cuda\n']' returned non-zero exit status 100
unit-kubernetes-worker-0: 01:40:33 ERROR juju.worker.uniter.operation hook "install" failed: exit status 1
unit-kubernetes-worker-0: 01:40:33 INFO juju.worker.uniter awaiting error resolution for "install" hook
unit-kubernetes-worker-1: 01:40:42 DEBUG unit.kubernetes-worker/1.install W: mdadm: /etc/mdadm/mdadm.conf defines no arrays.
unit-kubernetes-worker-0: 01:40:11 INFO juju.worker.uniter awaiting error resolution for "install" hook
unit-kubernetes-worker-0: 01:40:12 INFO unit.kubernetes-worker/0.juju-log Reactive main running for hook install
unit-kubernetes-worker-0: 01:40:12 INFO unit.kubernetes-worker/0.juju-log Initializing Snap Layer
unit-kubernetes-worker-0: 01:40:12 DEBUG unit.kubernetes-worker/0.install none
unit-kubernetes-worker-0: 01:40:12 DEBUG unit.kubernetes-worker/0.install Running reactive_handler_main for cuda.sh (test)
unit-kubernetes-worker-0: 01:40:12 DEBUG unit.kubernetes-worker/0.install Nothing to invoke
unit-kubernetes-worker-0: 01:40:12 DEBUG unit.kubernetes-worker/0.install End reactive_handler_main (test)
unit-kubernetes-worker-0: 01:40:12 DEBUG unit.kubernetes-worker/0.install Running reactive_handler_main for cuda.sh (test)
unit-kubernetes-worker-0: 01:40:12 DEBUG unit.kubernetes-worker/0.install Will invoke: install_cuda
unit-kubernetes-worker-0: 01:40:12 DEBUG unit.kubernetes-worker/0.install End reactive_handler_main (test)
unit-kubernetes-worker-0: 01:40:12 INFO unit.kubernetes-worker/0.juju-log Invoking reactive handler: reactive/kubernetes_worker.py:137:install_snaps
unit-kubernetes-worker-0: 01:40:13 INFO unit.kubernetes-worker/0.juju-log Refreshing kubectl from store
unit-kubernetes-worker-0: 01:40:14 INFO unit.kubernetes-worker/0.juju-log Refreshing kubelet from store
unit-kubernetes-worker-0: 01:40:15 INFO unit.kubernetes-worker/0.juju-log Refreshing kube-proxy from store
unit-kubernetes-worker-0: 01:40:15 DEBUG unit.kubernetes-worker/0.install Running reactive_handler_main for cuda.sh (test)
unit-kubernetes-worker-0: 01:40:15 DEBUG unit.kubernetes-worker/0.install Will invoke: install_cuda
unit-kubernetes-worker-0: 01:40:15 DEBUG unit.kubernetes-worker/0.install End reactive_handler_main (test)
unit-kubernetes-worker-0: 01:40:15 INFO unit.kubernetes-worker/0.juju-log Invoking reactive handler: reactive/docker.py:277:docker_template_update
unit-kubernetes-worker-0: 01:40:15 INFO unit.kubernetes-worker/0.juju-log Restarting docker service.
unit-kubernetes-worker-0: 01:40:15 INFO unit.kubernetes-worker/0.juju-log Reloading system daemons.
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Containers: 0
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install  Running: 0
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install  Paused: 0
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install  Stopped: 0
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Images: 0
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Server Version: 1.13.1
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Storage Driver: aufs
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install  Root Dir: /var/lib/docker/aufs
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install  Backing Filesystem: extfs
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install  Dirs: 0
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install  Dirperm1 Supported: true
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Logging Driver: json-file
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Cgroup Driver: cgroupfs
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Plugins: 
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install  Volume: local
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install  Network: bridge host macvlan null overlay
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Swarm: inactive
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Runtimes: runc
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Default Runtime: runc
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Init Binary: docker-init
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Security Options:
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install  apparmor
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install  seccomp
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install   Profile: default
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Kernel Version: 4.4.0-112-generic
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Operating System: Ubuntu 16.04.3 LTS
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install OSType: linux
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Architecture: x86_64
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install CPUs: 4
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Total Memory: 15.61 GiB
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Name: gpux1
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install ID: Q5UP:2YRZ:75PC:KOLZ:HKHK:KJ6P:XO5Y:EM6R:25ZI:R3QH:DVUZ:6AEK
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Docker Root Dir: /var/lib/docker
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Debug Mode (client): false
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Debug Mode (server): false
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Registry: https://index.docker.io/v1/
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install WARNING: No swap limit support
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Experimental: false
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Insecure Registries:
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install  127.0.0.0/8
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Live Restore Enabled: false
unit-kubernetes-worker-0: 01:40:18 INFO unit.kubernetes-worker/0.juju-log Invoking reactive handler: reactive/docker.py:189:enable_grub_cgroups
unit-kubernetes-worker-0: 01:40:18 INFO unit.kubernetes-worker/0.juju-log Invoking reactive handler: reactive/kubernetes_worker.py:917:fix_iptables_for_docker_1_13
unit-kubernetes-worker-0: 01:40:18 INFO unit.kubernetes-worker/0.juju-log Invoking reactive handler: reactive/cuda.sh "b'install_cuda\n'"
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Running reactive_handler_main for cuda.sh (invoke)
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install Invoking bash reactive handler: install_cuda
unit-kubernetes-worker-0: 01:40:18 INFO unit.kubernetes-worker/0.juju-log Blacklisting nouveau module
unit-kubernetes-worker-0: 01:40:18 DEBUG unit.kubernetes-worker/0.install update-initramfs: Generating /boot/initrd.img-4.4.0-112-generic
unit-kubernetes-worker-0: 01:40:27 DEBUG unit.kubernetes-worker/0.install W: mdadm: /etc/mdadm/mdadm.conf defines no arrays.
unit-kubernetes-worker-1: 01:40:30 INFO juju.worker.uniter awaiting error resolution for "install" hook
unit-kubernetes-worker-1: 01:40:30 INFO unit.kubernetes-worker/1.juju-log Reactive main running for hook install
unit-kubernetes-worker-1: 01:40:30 INFO unit.kubernetes-worker/1.juju-log Initializing Snap Layer
unit-kubernetes-worker-1: 01:40:31 DEBUG unit.kubernetes-worker/1.install none
unit-kubernetes-worker-1: 01:40:31 DEBUG unit.kubernetes-worker/1.install Running reactive_handler_main for cuda.sh (test)
unit-kubernetes-worker-1: 01:40:31 DEBUG unit.kubernetes-worker/1.install Nothing to invoke
unit-kubernetes-worker-1: 01:40:31 DEBUG unit.kubernetes-worker/1.install End reactive_handler_main (test)
unit-kubernetes-worker-1: 01:40:31 DEBUG unit.kubernetes-worker/1.install Running reactive_handler_main for cuda.sh (test)
unit-kubernetes-worker-1: 01:40:31 DEBUG unit.kubernetes-worker/1.install Will invoke: install_cuda
unit-kubernetes-worker-1: 01:40:31 DEBUG unit.kubernetes-worker/1.install End reactive_handler_main (test)
unit-kubernetes-worker-1: 01:40:31 INFO unit.kubernetes-worker/1.juju-log Invoking reactive handler: reactive/kubernetes_worker.py:357:toggle_ingress_state
unit-kubernetes-worker-1: 01:40:31 DEBUG unit.kubernetes-worker/1.install Running reactive_handler_main for cuda.sh (test)
unit-kubernetes-worker-1: 01:40:31 DEBUG unit.kubernetes-worker/1.install Will invoke: install_cuda
unit-kubernetes-worker-1: 01:40:31 DEBUG unit.kubernetes-worker/1.install End reactive_handler_main (test)
unit-kubernetes-worker-1: 01:40:31 INFO unit.kubernetes-worker/1.juju-log Invoking reactive handler: reactive/docker.py:189:enable_grub_cgroups
unit-kubernetes-worker-1: 01:40:31 INFO unit.kubernetes-worker/1.juju-log Invoking reactive handler: reactive/cuda.sh "b'install_cuda\n'"
unit-kubernetes-worker-1: 01:40:32 DEBUG unit.kubernetes-worker/1.install Running reactive_handler_main for cuda.sh (invoke)
unit-kubernetes-worker-1: 01:40:32 DEBUG unit.kubernetes-worker/1.install Invoking bash reactive handler: install_cuda
unit-kubernetes-worker-1: 01:40:32 INFO unit.kubernetes-worker/1.juju-log Blacklisting nouveau module
unit-kubernetes-worker-1: 01:40:32 DEBUG unit.kubernetes-worker/1.install update-initramfs: Generating /boot/initrd.img-4.4.0-112-generic
unit-kubernetes-worker-0: 01:40:32 INFO unit.kubernetes-worker/0.juju-log Installing linux-image-extra
unit-kubernetes-worker-0: 01:40:32 INFO unit.kubernetes-worker/0.juju-log Installing the nVidia driver
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install WARNING: The following packages cannot be authenticated!
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install   nvidia-390 libcuda1-390 libcuda1-375 nvidia-375 nvidia-390-dev
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install   nvidia-375-dev
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install E: There were unauthenticated packages and -y was used without --allow-unauthenticated
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install snap "kubectl" has no updates available
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install 
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install snap "kubelet" has no updates available
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install 
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install snap "kube-proxy" has no updates available
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install 
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install Traceback (most recent call last):
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install   File "/var/lib/juju/agents/unit-kubernetes-worker-0/charm/hooks/install", line 19, in <module>
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install     main()
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 113, in main
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install     bus.dispatch(restricted=restricted_mode)
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 364, in dispatch
unit-kubernetes-worker-0: 01:40:33 DEBUG unit.kubernetes-worker/0.install     _invoke(other_handlers)
unit-kubernetes-worker-1: 01:40:47 INFO unit.kubernetes-worker/1.juju-log Installing linux-image-extra
unit-kubernetes-worker-1: 01:40:47 INFO unit.kubernetes-worker/1.juju-log Installing the nVidia driver
unit-kubernetes-worker-1: 01:40:47 DEBUG unit.kubernetes-worker/1.install WARNING: The following packages cannot be authenticated!
unit-kubernetes-worker-1: 01:40:47 DEBUG unit.kubernetes-worker/1.install   nvidia-390 libcuda1-390 libcuda1-375 nvidia-375 nvidia-390-dev
unit-kubernetes-worker-1: 01:40:47 DEBUG unit.kubernetes-worker/1.install   nvidia-375-dev
unit-kubernetes-worker-1: 01:40:47 DEBUG unit.kubernetes-worker/1.install E: There were unauthenticated packages and -y was used without --allow-unauthenticated
unit-kubernetes-worker-1: 01:40:47 DEBUG unit.kubernetes-worker/1.install Traceback (most recent call last):
unit-kubernetes-worker-1: 01:40:47 DEBUG unit.kubernetes-worker/1.install   File "/var/lib/juju/agents/unit-kubernetes-worker-1/charm/hooks/install", line 19, in <module>
unit-kubernetes-worker-1: 01:40:47 DEBUG unit.kubernetes-worker/1.install     main()
unit-kubernetes-worker-1: 01:40:47 DEBUG unit.kubernetes-worker/1.install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 113, in main
unit-kubernetes-worker-1: 01:40:47 DEBUG unit.kubernetes-worker/1.install     bus.dispatch(restricted=restricted_mode)
unit-kubernetes-worker-1: 01:40:47 DEBUG unit.kubernetes-worker/1.install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 364, in dispatch
unit-kubernetes-worker-1: 01:40:47 DEBUG unit.kubernetes-worker/1.install     _invoke(other_handlers)
unit-kubernetes-worker-1: 01:40:47 DEBUG unit.kubernetes-worker/1.install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 340, in _invoke
unit-kubernetes-worker-1: 01:40:47 DEBUG unit.kubernetes-worker/1.install     handler.invoke()
unit-kubernetes-worker-1: 01:40:47 DEBUG unit.kubernetes-worker/1.install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 242, in invoke
unit-kubernetes-worker-1: 01:40:47 DEBUG unit.kubernetes-worker/1.install     subprocess.check_call([self._filepath, '--invoke', self._test_output], env=os.environ)
unit-kubernetes-worker-1: 01:40:47 DEBUG unit.kubernetes-worker/1.install   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
unit-kubernetes-worker-1: 01:40:47 DEBUG unit.kubernetes-worker/1.install     raise CalledProcessError(retcode, cmd)
unit-kubernetes-worker-1: 01:40:47 DEBUG unit.kubernetes-worker/1.install subprocess.CalledProcessError: Command '['/var/lib/juju/agents/unit-kubernetes-worker-1/charm/reactive/cuda.sh', '--invoke', b'install_cuda\n']' returned non-zero exit status 100
unit-kubernetes-worker-1: 01:40:47 ERROR juju.worker.uniter.operation hook "install" failed: exit status 1
unit-kubernetes-worker-1: 01:40:47 INFO juju.worker.uniter awaiting error resolution for "install" hook```

**Comment by ktsakalozos** [comment]
Thank you for reporting this @yaumeg . It looks like something changed on the nvidia repos. I wonder if the images you have in MaaS need some key refreshing. 
Would you be able to issue the following as soon as the workers are failing:
```
juju run --application kubernetes-worker  apt-key update
juju run --application kubernetes-worker  apt-get update
```

I any case we are currently working on aligning CDK with the recent changes in the GPU support that occurred in upstream v1.9. We will try to address the issue you are seeing as soon as possible.

**Comment by yaumeg** [comment]
Thank you for your answer. I tried apt-key / apt-get, and had errors related to public key availability:
```
Stderr: |
    W: GPG error: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release: The following signatures couldn t be verified because the public key is not available: NO_PUBKEY F60F4B3D7FA2AF80```
    W: The repository http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release is not signed.
  Stdout: |
    Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
    Hit:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
    Hit:3 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
    Hit:4 http://archive.ubuntu.com/ubuntu xenial-security InRelease
    Ign:5 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease
    Hit:6 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release
    Get:7 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release.gpg [801 B]
    Ign:7 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release.gpg
    Fetched 801 B in 0s (2461 B/s)
    Reading package lists...
  UnitId: kubernetes-worker/0
```
So I did this:
`juju run --application kubernetes-worker "apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F60F4B3D7FA2AF80"`

Followed by:
`juju run --application kubernetes-worker  apt-key update`
`juju run --application kubernetes-worker  apt-get update`

And my GPUs are now back in business !
