### ISSUE TITLE
Cannot disable all cdk-addons 

### ISSUE THREAD

**Issue by ktsakalozos** [juju-solutions/bundle-canonical-kubernetes#530]
If you try to disable dns and the dashboard you will see that the last thing you tried to disable is not stopped. For example after:
```
> juju config kubernetes-master enable-kube-dns=false
> juju config kubernetes-master enable-dashboard-addons=false
```

The dashboard is still there:
```
> kubectl get po --all-namespaces
NAMESPACE     NAME                                            READY     STATUS    RESTARTS   AGE
kube-system   heapster-v1.5.0-79579b9d8d-hpmst                4/4       Running   0          46m
kube-system   kubernetes-dashboard-5bd6f767c7-4nrjl           1/1       Running   0          50m
kube-system   monitoring-influxdb-grafana-v4-554f5d97-mz8ps   2/2       Running   0          50m
```

In the logs we get:
```
2018-04-01 13:50:20 DEBUG worker.uniter.jujuc server.go:178 hook context id "kubernetes-master/0-update-status-5147159022492089677"; dir "/var/lib/juju/agents/unit-kubernetes-master-0/charm"
2018-04-01 13:50:20 INFO juju-log Addons are not ready yet.
2018-04-01 13:50:41 INFO update-status error: at least one resource must be specified to use a selector
2018-04-01 13:50:41 INFO update-status Traceback (most recent call last):
2018-04-01 13:50:41 INFO update-status   File "/snap/cdk-addons/374/apply", line 106, in <module>
2018-04-01 13:50:41 INFO update-status     main()
2018-04-01 13:50:41 INFO update-status   File "/snap/cdk-addons/374/apply", line 14, in main
2018-04-01 13:50:41 INFO update-status     apply_addons()
2018-04-01 13:50:41 INFO update-status   File "/snap/cdk-addons/374/apply", line 77, in apply_addons
2018-04-01 13:50:41 INFO update-status     kubectl(*args)
2018-04-01 13:50:41 INFO update-status   File "/snap/cdk-addons/374/apply", line 86, in kubectl
2018-04-01 13:50:41 INFO update-status     return subprocess.check_output(cmd)
2018-04-01 13:50:41 INFO update-status   File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
2018-04-01 13:50:41 INFO update-status     **kwargs).stdout
2018-04-01 13:50:41 INFO update-status   File "/usr/lib/python3.5/subprocess.py", line 708, in run
2018-04-01 13:50:41 INFO update-status     output=stdout, stderr=stderr)
2018-04-01 13:50:41 INFO update-status subprocess.CalledProcessError: Command '['/snap/cdk-addons/374/kubectl', 'apply', '-f', '/root/snap/cdk-addons/374/addons', '--recursive', '--namespace=kube-system', '-l', 'kubernetes.io/cluster-service=true', '--prune=true', '--force']' returned non-zero exit status 1
```

Meaning that the `kubectl apply` we do against an empty directory (no cdk-addons results in an empty directory under `/root/snap/cdk-addons/current/addons`) is failing.

A workaround is to manually remove the deployment of the last thing you disabled.

**Comment by Cynerva** [comment]
Upstream issue: https://github.com/kubernetes/kubernetes/issues/40635
