### ISSUE TITLE
etcd, kubernetes-master, kubernetes-worker failing on s390x

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/bundle-canonical-kubernetes#552]
```
Model    Controller  Cloud/Region         Version  SLA
default  gkk-lxd     localhost/localhost  2.3.3    unsupported

App                    Version  Status   Scale  Charm                  Store       Rev  OS      Notes
easyrsa                3.0.1    active       1  easyrsa                jujucharms   39  ubuntu  
etcd                            error        3  etcd                   jujucharms   77  ubuntu  
flannel                         waiting      0  flannel                jujucharms   52  ubuntu  
kubeapi-load-balancer  1.10.3   active       1  kubeapi-load-balancer  jujucharms   57  ubuntu  exposed
kubernetes-master               error        1  kubernetes-master      jujucharms  102  ubuntu  
kubernetes-worker               error        3  kubernetes-worker      jujucharms  114  ubuntu  exposed

Unit                      Workload  Agent  Machine  Public address  Ports  Message
easyrsa/0*                active    idle   0        10.11.198.135          Certificate Authority connected.
etcd/0*                   error     idle   1        10.11.198.169          hook failed: "install"
etcd/1                    error     idle   2        10.11.198.24           hook failed: "install"
etcd/2                    error     idle   3        10.11.198.238          hook failed: "install"
kubeapi-load-balancer/0*  active    idle   4        10.11.198.61           NGINX is ready
kubernetes-master/0*      error     idle   5        10.11.198.242          hook failed: "install"
kubernetes-worker/0*      error     idle   6        10.11.198.195          hook failed: "install"
kubernetes-worker/1       error     idle   7        10.11.198.249          hook failed: "install"
kubernetes-worker/2       error     idle   8        10.11.198.83           hook failed: "install"
```

```
2018-04-12 13:52:11 DEBUG install Traceback (most recent call last):
2018-04-12 13:52:11 DEBUG install   File "/var/lib/juju/agents/unit-etcd-0/charm/hooks/install", line 19, in <module>
2018-04-12 13:52:11 DEBUG install     main()
2018-04-12 13:52:11 DEBUG install   File "/var/lib/juju/agents/unit-etcd-0/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 71, in main
2018-04-12 13:52:11 DEBUG install     hookenv._run_atstart()
2018-04-12 13:52:11 DEBUG install   File "/var/lib/juju/agents/unit-etcd-0/.venv/lib/python3.5/site-packages/charmhelpers/core/hookenv.py", line 1090, in _run_atstart
2018-04-12 13:52:11 DEBUG install     callback(*args, **kwargs)
2018-04-12 13:52:11 DEBUG install   File "/var/lib/juju/agents/unit-etcd-0/charm/reactive/snap.py", line 239, in configure_snap_enterprise_proxy
2018-04-12 13:52:11 DEBUG install     ensure_snapd_min_version('2.30')
2018-04-12 13:52:11 DEBUG install   File "/var/lib/juju/agents/unit-etcd-0/charm/reactive/snap.py", line 211, in ensure_snapd_min_version
2018-04-12 13:52:11 DEBUG install     add_source('distro-proposed', fail_invalid=True)
2018-04-12 13:52:11 DEBUG install   File "/var/lib/juju/agents/unit-etcd-0/.venv/lib/python3.5/site-packages/charmhelpers/fetch/ubuntu.py", line 390, in add_source
2018-04-12 13:52:11 DEBUG install     fn(*m.groups())
2018-04-12 13:52:11 DEBUG install   File "/var/lib/juju/agents/unit-etcd-0/.venv/lib/python3.5/site-packages/charmhelpers/fetch/ubuntu.py", line 418, in _add_proposed
2018-04-12 13:52:11 DEBUG install     .format(arch))
2018-04-12 13:52:11 DEBUG install charmhelpers.fetch.SourceConfigError: Arch s390x not supported for (distro-)proposed
2018-04-12 13:52:11 ERROR juju.worker.uniter.operation runhook.go:113 hook "install" failed: exit status 1
```
Reported in layer-snap at https://github.com/stub42/layer-snap/issues/13. Should be fixed by a new release of charmhelpers that includes https://github.com/juju/charm-helpers/pull/150.

**Comment by Cynerva** [comment]
This has been fixed with the new release of charmhelpers 0.18.8 (thanks @johnsca), but our stable charms still don't work on s390x since they ship with charmhelpers 0.18.7. We'll need to build and release new charms.
