### ISSUE TITLE
k8s-master stuck retrying addons when downgrading from 1.10 to 1.8.

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/bundle-canonical-kubernetes#553]
I noticed this in CI during a `test_upgrade` job for 1.8, which first deploys our stable bundles (which are currently 1.10) and then "upgrades" snaps to 1.8:

https://ci.kubernetes.juju.solutions/job/test-cdk/691/

This is fairly easy to repro outside of CI, and is more generically caused by downgrading the k8s master from stable to 1.8:
```bash
## Start with a stable bundle (currently 1.10/stable)
$ juju deploy cs:canonical-kubernetes-188
$ juju run --unit kubernetes-master/0 'snap list cdk-addons kube-apiserver'
Name            Version  Rev  Tracking  Developer  Notes
cdk-addons      1.10.0   386  1.10      canonical  -
kube-apiserver  1.10.0   393  1.10      canonical  -

## Downgrade to 1.8
$ juju config kubernetes-master channel=1.8/stable
$ juju run-action --wait kubernetes-master/0 upgrade
unit-kubernetes-master-0:
  id: 08c5cb40-3837-4a03-84a9-ee7d5189c8a3
  status: completed
$ juju run --unit kubernetes-master/0 'snap list cdk-addons kube-apiserver'
Name            Version  Rev  Tracking       Developer  Notes
cdk-addons      1.8.10   383  1.8/stable  canonical  -
kube-apiserver  1.8.10   390  1.8/stable  canonical  -
```

The master will look like this:
```
kubernetes-master/0*      waiting   idle   5        34.231.244.101  6443/tcp        Waiting to retry addon deployment
```

With a complaint about `apps/v1` for both `kubedns-controller` and `kubernetes-dashboard` in the debug log:
```
2018-04-13 15:24:12 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:637:configure_cdk_addons
2018-04-13 15:24:14 DEBUG upgrade Error from server: error when retrieving current configuration of:
2018-04-13 15:24:14 DEBUG upgrade &{0xc4208dc900 0xc4201567e0 kube-system kube-dns /root/snap/cdk-addons/383/addons/kubedns-controller.yaml 0xc42000c740 0xc42000c740  false}
2018-04-13 15:24:14 DEBUG upgrade from server for: "/root/snap/cdk-addons/383/addons/kubedns-controller.yaml": no kind "Deployment" is registered for version "apps/v1"
2018-04-13 15:24:14 DEBUG upgrade Error from server: error when retrieving current configuration of:
2018-04-13 15:24:14 DEBUG upgrade &{0xc421e54780 0xc420c1c700 kube-system kubernetes-dashboard /root/snap/cdk-addons/383/addons/kubernetes-dashboard.yaml 0xc4200df3f8 0xc4200df3f8  false}
2018-04-13 15:24:14 DEBUG upgrade from server for: "/root/snap/cdk-addons/383/addons/kubernetes-dashboard.yaml": no kind "Deployment" is registered for version "apps/v1"
2018-04-13 15:24:14 DEBUG upgrade Traceback (most recent call last):
2018-04-13 15:24:14 DEBUG upgrade   File "/snap/cdk-addons/383/apply", line 108, in <module>
2018-04-13 15:24:14 DEBUG upgrade     main()
2018-04-13 15:24:14 DEBUG upgrade   File "/snap/cdk-addons/383/apply", line 14, in main
2018-04-13 15:24:14 DEBUG upgrade     apply_addons()
2018-04-13 15:24:14 DEBUG upgrade   File "/snap/cdk-addons/383/apply", line 79, in apply_addons
2018-04-13 15:24:14 DEBUG upgrade     kubectl(*args)
2018-04-13 15:24:14 DEBUG upgrade   File "/snap/cdk-addons/383/apply", line 88, in kubectl
2018-04-13 15:24:14 DEBUG upgrade     return subprocess.check_output(cmd)
2018-04-13 15:24:14 DEBUG upgrade   File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
2018-04-13 15:24:14 DEBUG upgrade     **kwargs).stdout
2018-04-13 15:24:14 DEBUG upgrade   File "/usr/lib/python3.5/subprocess.py", line 708, in run
2018-04-13 15:24:14 DEBUG upgrade     output=stdout, stderr=stderr)
2018-04-13 15:24:14 DEBUG upgrade subprocess.CalledProcessError: Command '['/snap/cdk-addons/383/kubectl', 'apply', '-f', '/root/snap/cdk-addons/383/addons', '--recursive', '--namespace=kube-system', '-l', 'kubernetes.io/cluster-service=true', '--prune=true', '--force']' returned non-zero exit status 1
2018-04-13 15:24:14 INFO juju-log Addons are not ready yet.
2018-04-13 15:24:32 DEBUG collect-metrics Error from server: no kind "ReplicaSet" is registered for version "apps/v1"
```

Interestingly, deploying 1.9 and downgrading to 1.8 *does* work.  It's just when going -2 that it fails.  I don't think we support moving more than n+1 versions in either direction, so this may never get fixed, but wanted to note it here for fun.

**Comment by kwmonroe** [comment]
Full debug log for k8s-master:

[k8s-master-debug.log](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/1908699/k8s-master-debug.log)

**Comment by CalvinHartwell** [comment]
Are downgrades supported?

**Comment by hyperbolic2346** [comment]
I don't think we support downgrades and we addressed the tests trying to downgrade with https://github.com/juju-solutions/kubernetes-jenkins/pull/175
