### ISSUE TITLE
hook failure if you install with an attached snap resource, then try to switch to installing from the snap store

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/bundle-canonical-kubernetes#604]
I had a deployment where kubectl was installed locally from an attached snap resource. I tried to switch it back to installing from the snap store by attaching a zero-byte resource and calling the upgrade action. This resulted in a hook error:

```
unit-kubernetes-master-0: 11:34:36 INFO unit.kubernetes-master/0.juju-log Invoking reactive handler: reactive/kubernetes_master.py:268:do_upgrade
unit-kubernetes-master-0: 11:34:36 INFO unit.kubernetes-master/0.juju-log Refreshing kubectl from store
unit-kubernetes-master-0: 11:34:38 ERROR unit.kubernetes-master/0.juju-log Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-kubernetes-master-0/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 72, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-kubernetes-master-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 382, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-kubernetes-master-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 358, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-kubernetes-master-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 180, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-kubernetes-master-0/charm/reactive/kubernetes_master.py", line 270, in do_upgrade
    install_snaps()
  File "/var/lib/juju/agents/unit-kubernetes-master-0/charm/reactive/kubernetes_master.py", line 278, in install_snaps
    snap.install('kubectl', channel=channel, classic=True)
  File "lib/charms/layer/snap.py", line 40, in install
    refresh(snapname, **kw)
  File "lib/charms/layer/snap.py", line 71, in refresh
    _refresh_store(snapname, **kw)
  File "lib/charms/layer/snap.py", line 266, in _refresh_store
    stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['snap', 'refresh', '--channel=1.11/stable', '--classic', 'kubectl']' returned non-zero exit status 1

unit-kubernetes-master-0: 11:34:38 DEBUG unit.kubernetes-master/0.update-status error: local snap "kubectl" is unknown to the store, use --amend to proceed
unit-kubernetes-master-0: 11:34:38 DEBUG unit.kubernetes-master/0.update-status        anyway
```

Both kubernetes-master and kubernetes-worker had the same issue. I'd guess etcd is affected as well. Here are the full debug logs for the master and worker:

[kubernetes-master.log](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2156013/kubernetes-master.log)
[kubernetes-worker.log](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2156014/kubernetes-worker.log)

**Comment by Cynerva** [comment]
I hit this error while testing a related feature with a custom build of the charms, but I believe this issue will be present in today's stable charms as well. I'm going to confirm this.
