### ISSUE TITLE
Running into flannel error in update-status hook

### ISSUE THREAD

**Issue by SaMnCo** [juju-solutions/bundle-canonical-kubernetes#64]
Hello, 

Context: running on AWS, deployed OOTB working ok, then add a cuda charm to install CUDA on the kubernertes workers. This version of CUDA does install things, but does not reboot the unit anymore. 

Immediately after, I get 

```
$ juju status
MODEL    CONTROLLER  CLOUD/REGION   VERSION
default  k8s         aws/us-east-1  2.0-rc1

APP                    VERSION  STATUS   SCALE  CHARM                  STORE       REV  OS      NOTES
cuda                            active       3  cuda                   local         0  ubuntu  
easyrsa                3.0.1    active       1  easyrsa                jujucharms    1  ubuntu  
elasticsearch                   active       2  elasticsearch          jujucharms   18  ubuntu  
etcd                   2.2.5    active       3  etcd                   jujucharms   12  ubuntu  
filebeat                        active       4  filebeat               jujucharms    4  ubuntu  
flannel                0.6.1    error        4  flannel                jujucharms    1  ubuntu  
kibana                          active       1  kibana                 jujucharms   14  ubuntu  
kubeapi-load-balancer  1.10.0   active       1  kubeapi-load-balancer  jujucharms    1  ubuntu  exposed
kubernetes-master      1.4.0    active       1  kubernetes-master      jujucharms    1  ubuntu  
kubernetes-worker      1.4.0    error        3  kubernetes-worker      jujucharms    1  ubuntu  exposed
nfs                             unknown      1  nfs                    jujucharms    0  ubuntu  
topbeat                         active       3  topbeat                jujucharms    4  ubuntu  
```

If I resolve the issue with Juju, the log gives me (also full file attached)

```
unit-flannel-0: 18:47:55 ERROR juju.worker.uniter.operation hook "update-status" failed: exit status 1
unit-flannel-0: 18:47:55 INFO juju.worker.uniter awaiting error resolution for "update-status" hook
unit-flannel-0: 18:48:04 INFO juju.worker.leadership flannel/0 will renew flannel leadership at 2016-09-27 16:48:34.285410085 +0000 UTC
unit-flannel-0: 18:48:05 INFO juju.worker.uniter awaiting error resolution for "update-status" hook
unit-flannel-0: 18:48:05 INFO worker.uniter.jujuc running hook tool "config-get" ["--format=json"]
unit-flannel-0: 18:48:06 INFO worker.uniter.jujuc running hook tool "juju-log" ["-l" "INFO" "Reactive main running for hook update-status"]
unit-flannel-0: 18:48:06 INFO unit.flannel/0.juju-log Reactive main running for hook update-status
unit-flannel-0: 18:48:06 INFO worker.uniter.jujuc running hook tool "juju-log" ["-l" "INFO" "Invoking reactive handler: reactive/flannel.py:185:set_flannel_version"]
unit-flannel-0: 18:48:06 INFO unit.flannel/0.juju-log Invoking reactive handler: reactive/flannel.py:185:set_flannel_version
unit-flannel-0: 18:48:06 INFO unit.flannel/0.update-status Traceback (most recent call last):
unit-flannel-0: 18:48:06 INFO unit.flannel/0.update-status   File "/var/lib/juju/agents/unit-flannel-0/charm/hooks/update-status", line 19, in <module>
unit-flannel-0: 18:48:06 INFO unit.flannel/0.update-status     main()
unit-flannel-0: 18:48:06 INFO unit.flannel/0.update-status   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
unit-flannel-0: 18:48:06 INFO unit.flannel/0.update-status     bus.dispatch()
unit-flannel-0: 18:48:06 INFO unit.flannel/0.update-status   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
unit-flannel-0: 18:48:06 INFO unit.flannel/0.update-status     _invoke(other_handlers)
unit-flannel-0: 18:48:06 INFO unit.flannel/0.update-status   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
unit-flannel-0: 18:48:06 INFO unit.flannel/0.update-status     handler.invoke()
unit-flannel-0: 18:48:06 INFO unit.flannel/0.update-status   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
unit-flannel-0: 18:48:06 INFO unit.flannel/0.update-status     self._action(*args)
unit-flannel-0: 18:48:06 INFO unit.flannel/0.update-status   File "/var/lib/juju/agents/unit-flannel-0/charm/reactive/flannel.py", line 198, in set_flannel_version
unit-flannel-0: 18:48:06 INFO unit.flannel/0.update-status     hookenv.application_version_set(version.split(b'v')[-1].rstrip())
unit-flannel-0: 18:48:06 INFO unit.flannel/0.update-status AttributeError: module 'charmhelpers.core.hookenv' has no attribute 'application_version_set'
unit-flannel-0: 18:48:06 ERROR juju.worker.uniter.operation hook "update-status" failed: exit status 1
unit-flannel-0: 18:48:06 INFO juju.worker.uniter awaiting error resolution for "update-status" hook
unit-flannel-0: 18:48:27 INFO juju.worker.uniter awaiting error resolution for "update-status" hook
unit-flannel-0: 18:48:27 INFO worker.uniter.jujuc running hook tool "config-get" ["--format=json"]
unit-flannel-0: 18:48:27 INFO worker.uniter.jujuc running hook tool "juju-log" ["-l" "INFO" "Reactive main running for hook update-status"]
unit-flannel-0: 18:48:27 INFO unit.flannel/0.juju-log Reactive main running for hook update-status
unit-flannel-0: 18:48:27 INFO worker.uniter.jujuc running hook tool "juju-log" ["-l" "INFO" "Invoking reactive handler: reactive/flannel.py:185:set_flannel_version"]
unit-flannel-0: 18:48:27 INFO unit.flannel/0.juju-log Invoking reactive handler: reactive/flannel.py:185:set_flannel_version
unit-flannel-0: 18:48:27 INFO unit.flannel/0.update-status Traceback (most recent call last):
unit-flannel-0: 18:48:27 INFO unit.flannel/0.update-status   File "/var/lib/juju/agents/unit-flannel-0/charm/hooks/update-status", line 19, in <module>
unit-flannel-0: 18:48:27 INFO unit.flannel/0.update-status     main()
unit-flannel-0: 18:48:27 INFO unit.flannel/0.update-status   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
unit-flannel-0: 18:48:27 INFO unit.flannel/0.update-status     bus.dispatch()
unit-flannel-0: 18:48:27 INFO unit.flannel/0.update-status   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
unit-flannel-0: 18:48:27 INFO unit.flannel/0.update-status     _invoke(other_handlers)
```

It is to note that the cluster is still OK and seems to be working, pods answer etc etc. So it may be just cosmetic. 

[flannel.log.zip](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/496168/flannel.log.zip)
[all.log.zip](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/496177/all.log.zip)

**Comment by mbruzek** [comment]
@SaMnCo I don't know what CUDA installs or does but I suspect it installed an older version of charmhelpers without the application_version_set() method. 

The log indicates that flannel was running along just fine setting application version as recently as 18:27:

    unit-flannel-0: 18:27:46 INFO worker.uniter.jujuc running hook tool "application-version-set" ["0.6.1"]

Then at around 18:35:29 charmhelpers.core.hookenv no longer had that method. I suspect your CUDA install changed the version of charmhelpers on that system.
