### ISSUE TITLE
hook failure due to "Missing authentication mechanism."

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/bundle-canonical-kubernetes#656]
I don't think this can happen in stable, but I hit this error on an edge deployment:

```
unit-kubernetes-master-0: 11:10:54 ERROR unit.kubernetes-master/0.juju-log kube-api-endpoint:1: Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-kubernetes-master-0/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 73, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-kubernetes-master-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 382, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-kubernetes-master-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 358, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-kubernetes-master-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 180, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-kubernetes-master-0/charm/reactive/kubernetes_master.py", line 820, in create_self_config
    build_kubeconfig(server)
  File "/var/lib/juju/agents/unit-kubernetes-master-0/charm/reactive/kubernetes_master.py", line 1098, in build_kubeconfig
    token=proxy_token, user='kube-proxy')
  File "lib/charms/layer/kubernetes_common.py", line 267, in create_kubeconfig
    raise ValueError('Missing authentication mechanism.')
ValueError: Missing authentication mechanism.
unit-kubernetes-master-0: 11:10:54 ERROR juju.worker.uniter.operation hook "kube-api-endpoint-relation-joined" failed: exit status 1
```

Looks like a race condition. The code here assumes a kube-proxy token is available:
https://github.com/juju-solutions/kubernetes/blob/8ee319d17ccf81cfddc216b8a0e5fd42c7eec85e/cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py#L1096-L1098

However, it's being called before this code that creates the token:
https://github.com/juju-solutions/kubernetes/blob/8ee319d17ccf81cfddc216b8a0e5fd42c7eec85e/cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py#L635

Debug stuff:
[bundle.yaml.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2416134/bundle.yaml.txt) that I used (from edge, but with `series: xenial` and a modified kubernetes-worker)
[debug-log.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2416125/debug-log.txt)
[charm-unitdata.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2416126/charm-unitdata.txt)

**Comment by Cynerva** [comment]
Fixed by @hyperbolic2346, thanks!
