### ISSUE TITLE
Kubernetes worker - NVidia card

### ISSUE THREAD

**Issue by boucherv** [juju-solutions/bundle-canonical-kubernetes#664]
Since one week-end, the Kubernetes worker charms always fail to install if a NVidia card exist on the worker node. It looks like the **_NVidia PPA_** key wasn't the right one:

2018-10-09 20:31:23 DEBUG install WARNING: The following packages cannot be authenticated!
2018-10-09 20:31:23 DEBUG install   libnvidia-container1 libnvidia-container-tools nvidia-container-runtime-hook
2018-10-09 20:31:23 DEBUG install   nvidia-container-runtime nvidia-docker2
2018-10-09 20:31:23 DEBUG install E: There were **unauthenticated packages** and -y was used without --allow-unauthenticated
2018-10-09 20:31:23 ERROR juju-log Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-kubernetes-worker-9/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 73, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-kubernetes-worker-9/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-kubernetes-worker-9/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-kubernetes-worker-9/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-kubernetes-worker-9/charm/reactive/docker.py", line 128, in install
    install_from_nvidia_apt()
  File "/var/lib/juju/agents/unit-kubernetes-worker-9/charm/reactive/docker.py", line 298, in install_from_nvidia_apt
    nv_container_runtime], fatal=True)
  File "/var/lib/juju/agents/unit-kubernetes-worker-9/.venv/lib/python3.5/site-packages/charmhelpers/fetch/ubuntu.py", line 216, in apt_install
    _run_apt_command(cmd, fatal)
  File "/var/lib/juju/agents/unit-kubernetes-worker-9/.venv/lib/python3.5/site-packages/charmhelpers/fetch/ubuntu.py", line 576, in _run_apt_command
    retry_message="Couldn't acquire DPKG lock")
  File "/var/lib/juju/agents/unit-kubernetes-worker-9/.venv/lib/python3.5/site-packages/charmhelpers/fetch/ubuntu.py", line 552, in _run_with_retries
    result = subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-get', '--assume-yes', '--option=Dpkg::Options::=--force-confold', 'install', 'cuda-drivers', 'docker-ce=17.12.1~ce-0~ubuntu', 'nvidia-docker2=2.0.3+docker17.12.1-1', 'nvidia-container-runtime=2.0.0+docker17.12.1-1']' returned non-zero exit status 100

The issue are the same with a old charm version or the new one! Thanks in advance

**Comment by ktsakalozos** [comment]
Hi @boucherv ,

Thank you for reporting this. As you can see a PR is already up and the fix will be released soon with a new kubernetes worker.

A workaround for now would be to `apt-key adv --fetch-keys https://nvidia.github.io/nvidia-docker/gpgkey` in the failing workers and to
```
juju config kubernetes-worker cuda_repo=10.0.130-1
juju config kubernetes-worker nvidia-docker-package=nvidia-docker2
juju config kubernetes-worker nvidia-container-runtime-package=nvidia-container-runtime
juju config kubernetes-worker docker-ce-package=docker-ce
```

Apologies for the inconvenience caused.

**Comment by ktsakalozos** [comment]
The fix is released in the lates kubernetes-worker https://jujucharms.com/u/containers/kubernetes-worker/239
