### ISSUE TITLE
error: snap "etcd" is not compatible with --classic

### ISSUE THREAD

**Issue by darkstar** [juju-solutions/bundle-canonical-kubernetes#727]
I'm trying to bootstrap kubernetes in a vsphere environment.

The etcd units don't get created correctly (juju status shows `hook failed: "install"` and, briefly, `(install) Missing relation to certificate authority.`, even though that relation definitely exists)

When checking the juju.log in those units (`sudo cat /var/log/juju/unit-etcd-0.log`), I see the following error:

```
2019-01-29 14:16:06 DEBUG juju-log Changing permissions on existing content: 33277 -> 292
2019-01-29 14:16:06 DEBUG juju-log Changing permissions on existing content: 33060 -> 292
2019-01-29 14:16:06 INFO juju-log Invoking reactive handler: reactive/etcd.py:100:missing_relation_notice
2019-01-29 14:16:06 INFO juju-log Invoking reactive handler: reactive/etcd.py:277:snap_install
2019-01-29 14:16:07 INFO juju-log Installing etcd from store
2019-01-29 14:16:19 ERROR juju-log Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-etcd-0/.venv/lib/python3.6/site-packages/charms/reactive/__init__.py", line 73, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-etcd-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-etcd-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-etcd-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-etcd-0/charm/reactive/etcd.py", line 281, in snap_install
    snap.install('etcd', channel=channel, classic=True)
  File "lib/charms/layer/snap.py", line 54, in install
    _install_store(snapname, **kw)
  File "lib/charms/layer/snap.py", line 289, in _install_store
    stderr=subprocess.STDOUT)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['snap', 'install', '--channel=3.2/stable', '--classic', 'etcd']' returned non-zero exit status 1.

2019-01-29 14:16:19 DEBUG install error: snap "etcd" is not compatible with --classic
2019-01-29 14:16:19 DEBUG install
2019-01-29 14:16:19 DEBUG install error: snap "etcd" is not compatible with --classic
2019-01-29 14:16:19 DEBUG install
2019-01-29 14:16:19 DEBUG install error: snap "etcd" is not compatible with --classic
2019-01-29 14:16:19 DEBUG install
```

I was trying to follow [this guide](https://blog.ubuntu.com/2018/08/23/vsphere), so I was using `juju deploy cs:canonical-kubernetes` instead of `conjure-up`

Any ideas?

**Comment by hyperbolic2346** [comment]
This is something that broke under us on a snapd upgrade. It is fixed with https://github.com/juju-solutions/layer-etcd/pull/147, but that will take a little time to publish. We are working on doing that now.

**Comment by darkstar** [comment]
Ah. I searched for a bit but I didn't find that one. Thanks!

I'm now trying to remove the etcd app again, `juju remove-application etcd` doesn't seem to work, neither does `juju remove-unit etcd/0` ... they're still stuck in the "installing charm" step.
I guess I'll have to forcibly kill them somehow?

**Comment by hyperbolic2346** [comment]
you can use `juju resolved --no-retry` to push juju along until things are happy enough to run your removal.

You can do is build the charm yourself and deploy your built version. That might open a new can of worms for you depending on your setup, but grabbing the etcdd charm code and running `charm build etcd-path` would grab the latest layer, which has the fix.

We should have this fixed "soon(tm)"

**Comment by hyperbolic2346** [comment]
cs:~containers/etcd-378 is now in stable and that should fix this issue.

**Comment by tvansteenburgh** [comment]
Stable bundles have been updated to use etcd-378.
