### ISSUE TITLE
Hook failure on MAAS behind a proxy.

### ISSUE THREAD

**Issue by seman** [juju-solutions/bundle-canonical-kubernetes#92]
The `elasticsearch` charm fails when it is deployed to a machine behind a proxy.

https://pastebin.canonical.com/167904/

`2016-10-13 22:49:49 INFO install Setting up ansible (1.5.4+dfsg-1) ...
2016-10-13 22:49:49 INFO install Processing triggers for libc-bin (2.19-0ubuntu6.9) ...
2016-10-13 22:49:49 INFO juju-log /usr/bin/rsync -r --delete --executability ansible_module_backports /usr/share/ansible
2016-10-13 22:49:50 INFO install 
2016-10-13 22:49:50 INFO install PLAY [localhost] ************************************************************** 
2016-10-13 22:49:50 INFO install 
2016-10-13 22:49:50 INFO install GATHERING FACTS *************************************************************** 
2016-10-13 22:49:50 INFO install ok: [localhost]
2016-10-13 22:49:50 INFO install 
2016-10-13 22:49:50 INFO install TASK: [Add apt key.] ********************************************************** 
2016-10-13 22:50:16 INFO juju.worker.leadership tracker.go:184 elasticsearch/0 will renew elasticsearch leadership at 2016-10-13 22:50:46.785867 +0000 UTC
2016-10-13 22:50:20 INFO install failed: [localhost] => {"failed": true, "item": "", "traceback": "Traceback (most recent call last):\n  File \"/.ansible/tmp/ansible-tmp-1476398990.53-114100582731205/apt_key\", line 144, in download_key\n    return rsp.read()\nAttributeError: 'NoneType' object has no attribute 'read'\n"}
2016-10-13 22:50:20 INFO install msg: error getting key id from url
2016-10-13 22:50:20 INFO install 
2016-10-13 22:50:20 INFO install FATAL: all hosts have already failed -- aborting
2016-10-13 22:50:20 INFO install 
2016-10-13 22:50:20 INFO install PLAY RECAP ******************************************************************** 
2016-10-13 22:50:20 INFO install localhost                  : ok=1    changed=0    unreachable=0    failed=1   
2016-10-13 22:50:20 INFO install 
2016-10-13 22:50:20 INFO install Traceback (most recent call last):
2016-10-13 22:50:20 INFO install   File "/var/lib/juju/agents/unit-elasticsearch-0/charm/hooks/install", line 101, in <module>
2016-10-13 22:50:20 INFO install     hooks.execute(sys.argv)
2016-10-13 22:50:20 INFO install   File "/var/lib/juju/agents/unit-elasticsearch-0/charm/hooks/charmhelpers/contrib/ansible/__init__.py", line 171, in execute
2016-10-13 22:50:20 INFO install     self.playbook_path, tags=[hook_name])
2016-10-13 22:50:20 INFO install   File "/var/lib/juju/agents/unit-elasticsearch-0/charm/hooks/charmhelpers/contrib/ansible/__init__.py", line 116, in apply_playbook
2016-10-13 22:50:20 INFO install     subprocess.check_call(call, env=env)
2016-10-13 22:50:20 INFO install   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
2016-10-13 22:50:20 INFO install     raise CalledProcessError(retcode, cmd)
2016-10-13 22:50:20 INFO install subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'playbook.yaml', '--tags', 'install']' returned non-zero exit status 2
2016-10-13 22:50:20 ERROR juju.worker.uniter.operation runhook.go:107 hook "install" failed: exit status 1
2`

**Comment by marcoceppi** [comment]
This is a known issue with Elasticsearch. Elasticsearch is being re-written so this doesn't cause a failure.

**Comment by chuckbutler** [comment]
Known issue yes, but still a problem. I'd like to keep this issue open until either the new elastic search charm lands or we update the existing charm to not be so finicky in egress limited networks.
