### ISSUE TITLE
SDN Plugin relationship not properly cleaning states on remove-relation

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/bundle-canonical-kubernetes#94]
The SDN plugin interface doesn't appear to be signalling to the kubernetes workloads that it is undergoing removal and reconfiguration of the software defined network.

This effects:
- DNS Pod Deployment
- Master/Node networking

Upon removing the relationship for the SDN-Plugin:

```
unit-kubernetes-master-0: 13:25:04 INFO unit.kubernetes-master/0.juju-log sdn-plugin:6: Invoking reactive handler: reactive/kubernetes_master.py:157:send_cluster_dns_detail
unit-kubernetes-master-0: 13:25:04 INFO unit.kubernetes-master/0.sdn-plugin-relation-broken Traceback (most recent call last):
unit-kubernetes-master-0: 13:25:04 INFO unit.kubernetes-master/0.sdn-plugin-relation-broken   File "/var/lib/juju/agents/unit-kubernetes-master-0/charm/hooks/sdn-plugin-relation-broken", line 19, in <module>
unit-kubernetes-master-0: 13:25:04 INFO unit.kubernetes-master/0.sdn-plugin-relation-broken     main()
unit-kubernetes-master-0: 13:25:04 INFO unit.kubernetes-master/0.sdn-plugin-relation-broken   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
unit-kubernetes-master-0: 13:25:04 INFO unit.kubernetes-master/0.sdn-plugin-relation-broken     bus.dispatch()
unit-kubernetes-master-0: 13:25:04 INFO unit.kubernetes-master/0.sdn-plugin-relation-broken   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
unit-kubernetes-master-0: 13:25:04 INFO unit.kubernetes-master/0.sdn-plugin-relation-broken     _invoke(other_handlers)
unit-kubernetes-master-0: 13:25:04 INFO unit.kubernetes-master/0.sdn-plugin-relation-broken   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
unit-kubernetes-master-0: 13:25:04 INFO unit.kubernetes-master/0.sdn-plugin-relation-broken     handler.invoke()
unit-kubernetes-master-0: 13:25:04 INFO unit.kubernetes-master/0.sdn-plugin-relation-broken   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
unit-kubernetes-master-0: 13:25:04 INFO unit.kubernetes-master/0.sdn-plugin-relation-broken     self._action(*args)
unit-kubernetes-master-0: 13:25:04 INFO unit.kubernetes-master/0.sdn-plugin-relation-broken   File "/var/lib/juju/agents/unit-kubernetes-master-0/charm/reactive/kubernetes_master.py", line 160, in send_cluster_dns_detail
unit-kubernetes-master-0: 13:25:04 INFO unit.kubernetes-master/0.sdn-plugin-relation-broken     sdn_ip = get_dns_ip(details['cidr'])
unit-kubernetes-master-0: 13:25:04 INFO unit.kubernetes-master/0.sdn-plugin-relation-broken   File "/var/lib/juju/agents/unit-kubernetes-master-0/charm/reactive/kubernetes_master.py", line 492, in get_dns_ip
unit-kubernetes-master-0: 13:25:04 INFO unit.kubernetes-master/0.sdn-plugin-relation-broken     ip = cidr.split('/')[0]
unit-kubernetes-master-0: 13:25:04 INFO unit.kubernetes-master/0.sdn-plugin-relation-broken AttributeError: 'NoneType' object has no attribute 'split'
```

As you can see, the broken hook would be run in the context of having no further communication with the flannel subordinate (in this case) and its still attempting to parse the subnet and schedule the DNS pods. Which is indicative of the states not being properly cleaned up upon the removal of the relation.

**Comment by wwwtyro** [comment]
I think with @chuckbutler's changes and the following PR, we're probably good here.

https://github.com/juju-solutions/interface-sdn-plugin/pull/5

**Comment by chuckbutler** [comment]
Wow, yep. I missed this. We're g2g on this issue
