### ISSUE TITLE
kubernetes-worker cleanup fails and halts execution when apiserver not reachable.

### ISSUE THREAD

**Issue by SaMnCo** [juju-solutions/bundle-canonical-kubernetes#95]
When tearing down a manually deployed cluster to repurpose some machines, not everything goes away: 

`juju remove-application kubernetes-worker` 
# Stop hook fails

```
2016-10-17 13:49:05 INFO juju.worker.leadership tracker.go:184 kubernetes-worker/0 will renew kubernetes-worker leadership at 2016-10-17 09:49:35.581715 -0400 EDT
2016-10-17 13:49:06 INFO juju.worker.uniter resolver.go:100 awaiting error resolution for "stop" hook
2016-10-17 13:49:06 INFO juju-log Reactive main running for hook stop
2016-10-17 13:49:06 INFO juju-log Invoking reactive handler: reactive/kubernetes_worker.py:25:shutdown
2016-10-17 13:49:07 INFO juju-log Executing ['kubectl', '--kubeconfig=/srv/kubernetes/config', 'delete', 'node', 'fnode3-6']
2016-10-17 13:49:07 INFO stop Error from server: nodes "fnode3-6" not found
2016-10-17 13:49:07 INFO stop Traceback (most recent call last):
2016-10-17 13:49:07 INFO stop   File "/var/lib/juju/agents/unit-kubernetes-worker-0/charm/hooks/stop", line 19, in <module>
2016-10-17 13:49:07 INFO stop     main()
2016-10-17 13:49:07 INFO stop   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
2016-10-17 13:49:07 INFO stop     bus.dispatch()
2016-10-17 13:49:07 INFO stop   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 426, in dispatch
2016-10-17 13:49:07 INFO stop     _invoke(hook_handlers)
2016-10-17 13:49:07 INFO stop   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
2016-10-17 13:49:07 INFO stop     handler.invoke()
2016-10-17 13:49:07 INFO stop   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
2016-10-17 13:49:07 INFO stop     self._action(*args)
2016-10-17 13:49:07 INFO stop   File "/var/lib/juju/agents/unit-kubernetes-worker-0/charm/reactive/kubernetes_worker.py", line 33, in shutdown
2016-10-17 13:49:07 INFO stop     kubectl('delete', 'node', gethostname())
2016-10-17 13:49:07 INFO stop   File "/var/lib/juju/agents/unit-kubernetes-worker-0/charm/reactive/kubernetes_worker.py", line 363, in kubectl
2016-10-17 13:49:07 INFO stop     return check_output(command)
2016-10-17 13:49:07 INFO stop   File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
2016-10-17 13:49:07 INFO stop     **kwargs).stdout
2016-10-17 13:49:07 INFO stop   File "/usr/lib/python3.5/subprocess.py", line 708, in run
2016-10-17 13:49:07 INFO stop     output=stdout, stderr=stderr)
2016-10-17 13:49:07 INFO stop subprocess.CalledProcessError: Command '['kubectl', '--kubeconfig=/srv/kubernetes/config', 'delete', 'node', 'fnode3-6']' returned non-zero exit status 1
2016-10-17 13:49:07 ERROR juju.worker.uniter.operation runhook.go:107 hook "stop" failed: exit status 1
2016-10-17 13:49:07 INFO juju.worker.uniter resolver.go:100 awaiting error resolution for "stop" hook
```

This can be fixed with a `juju resolved --no-retry`
# File Clean up
- /etc/ssl/certs/kubernetes-worker.pem
- /usr/local/share/ca-certificates/kubernetes-worker.crt
- /srv/kubernetes (folder)
- kubelet.service -> /lib/systemd/system/kubelet.service (in /etc/systemd/system/multi-user.target.wants)
- kube-proxy.service -> /lib/systemd/system/kube-proxy.service (/etc/systemd/system/multi-user.target.wants)
- /etc/default/kube-proxy
- /etc/default/kube-default
- /etc/default/kubelet
- /usr/local/bin/kube-proxy
- /usr/local/bin/kubectl
- /usr/local/bin/kubelet
- /var/lib/kubelet
# Services still working
- kube-proxy 
- Kubelet

```
/usr/local/bin/kube-proxy --logtostderr=true --v=0 --master=https://250.248.110.50:443 --kubeconfig=/srv/kubernetes/config
```
# Notes

This deployment was never complete (could not get to run) so it is possible that tearing down a working cluster would have more things to clean up.

**Comment by chuckbutler** [comment]
@SaMnCo - To scope this properly: did you remove the apiserver before removing the worker?

**Comment by SaMnCo** [comment]
No, I removed the worker first. I'm doing step by step tear down.

**Comment by wwwtyro** [comment]
@SaMnCo something is strange here - where did that `fnode3-6` name come from?

**Comment by mbruzek** [comment]
@SaMnCo I know of zero charms that clean up all the files that are installed. This seems like an edge case related only to manual provider. Can you please email the juju list with this request/suggestion? If the larger community wants to spend time on cleaning all the files we can add that to the road map but it will detract from adding new features to this bundle.

**Comment by wwwtyro** [comment]
@SaMnCo I just tested the code path for the stacktrace you posted. I saw no issue. The only thing I can think of that might be going on here is that your kubernetes node names aren't matching your hostnames for some reason. Do you know if anything was done that might affect that mapping?

**Comment by chuckbutler** [comment]
@wwwtyro the `fnode3-6` would be the result of `socket.gethostname()`

Kubernetes nodes are registered using the hostname, and K8s itself assumes host-name resolveability, which denotes there should be some form of dns running in the environment to provide that resolution.

In the case of the manual provider, this is likely not the case, and will be a larger problem than node-registration/unregistration. When you kubectl exec, it attempts to contact that host via the hostname.

Unfortunate, but the current state of things.

**Comment by SaMnCo** [comment]
@chuckbutler right on spot. I had to add cross DNS between nodes via the /etc/hosts file to make it work in this context. 
The DNS of the environment wasn't working here. 

@wwwtyro there are a number of corner cases in this work: it's a manual provider, ppc64le, with a mix of overlays to make the deployment possible (fan + flannel). The specific issue here was that the worker would not register itself to the master (DNS + Flannel problem), therefore making the command fail. So essentially, this means tearing down a k8s cluster that is not fully deployed will fail. This could be fixed by adding a try/catch on the execution of kubectl delete node, but I don't think it is a high priority.

**Comment by chuckbutler** [comment]
https://github.com/kubernetes/kubernetes/blob/master/cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py#L164-L165

Wrap these commands in a  try/except.

**Comment by tvansteenburgh** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/48144
