### ISSUE TITLE
kubernetes-master cleanup not complete

### ISSUE THREAD

**Issue by SaMnCo** [juju-solutions/bundle-canonical-kubernetes#96]
```juju remove-application kubernetes-master``` gives: 

# hook failing

kubernetes-master/1*      error     idle   5        250.248.79.1     6443/tcp  hook failed: "cluster-dns-relation-broken" for kubernetes-worker:kube-dns

```
2016-10-17 14:29:02 INFO juju.worker.leadership tracker.go:184 kubernetes-master/1 will renew kubernetes-master leadership at 2016-10-17 10:29:32.099836 -0400 EDT
2016-10-17 14:29:23 INFO juju.worker.uniter resolver.go:100 awaiting error resolution for "relation-broken" hook
2016-10-17 14:29:23 INFO juju-log cluster-dns:19: Reactive main running for hook cluster-dns-relation-broken
2016-10-17 14:29:23 INFO juju-log cluster-dns:19: Invoking reactive handler: reactive/kubernetes_master.py:171:send_data
2016-10-17 14:29:23 INFO cluster-dns-relation-broken Traceback (most recent call last):
2016-10-17 14:29:23 INFO cluster-dns-relation-broken   File "/var/lib/juju/agents/unit-kubernetes-master-1/charm/hooks/cluster-dns-relation-broken", line 19, in <module>
2016-10-17 14:29:23 INFO cluster-dns-relation-broken     main()
2016-10-17 14:29:23 INFO cluster-dns-relation-broken   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
2016-10-17 14:29:23 INFO cluster-dns-relation-broken     bus.dispatch()
2016-10-17 14:29:23 INFO cluster-dns-relation-broken   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
2016-10-17 14:29:23 INFO cluster-dns-relation-broken     _invoke(other_handlers)
2016-10-17 14:29:23 INFO cluster-dns-relation-broken   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
2016-10-17 14:29:23 INFO cluster-dns-relation-broken     handler.invoke()
2016-10-17 14:29:23 INFO cluster-dns-relation-broken   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
2016-10-17 14:29:23 INFO cluster-dns-relation-broken     self._action(*args)
2016-10-17 14:29:23 INFO cluster-dns-relation-broken   File "/var/lib/juju/agents/unit-kubernetes-master-1/charm/reactive/kubernetes_master.py", line 180, in send_data
2016-10-17 14:29:23 INFO cluster-dns-relation-broken     sdn_ip = get_sdn_ip(sdn_cidr)
2016-10-17 14:29:23 INFO cluster-dns-relation-broken   File "/var/lib/juju/agents/unit-kubernetes-master-1/charm/reactive/kubernetes_master.py", line 500, in get_sdn_ip
2016-10-17 14:29:23 INFO cluster-dns-relation-broken     ip = cidr.split('/')[0]
2016-10-17 14:29:23 INFO cluster-dns-relation-broken AttributeError: 'NoneType' object has no attribute 'split'
2016-10-17 14:29:23 ERROR juju.worker.uniter.operation runhook.go:107 hook "cluster-dns-relation-broken" failed: exit status 1
2016-10-17 14:29:23 INFO juju.worker.uniter resolver.go:100 awaiting error resolution for "relation-broken" hook
2016-10-17 14:29:32 INFO juju.worker.leadership tracker.go:184 kubernetes-master/1 will renew kubernetes-master leadership at 2016-10-17 10:30:02.09994 -0400 EDT

```
If doing ```resolved --no-retry``` we get: 

```

2016-10-17 14:31:37 INFO juju.worker.uniter resolver.go:100 awaiting error resolution for "relation-broken" hook
2016-10-17 14:31:38 INFO juju-log Reactive main running for hook leader-settings-changed
2016-10-17 14:31:38 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:164:push_service_data
2016-10-17 14:31:38 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:120:set_app_version
2016-10-17 14:31:39 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:209:gather_sdn_data
2016-10-17 14:31:39 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:171:send_data
2016-10-17 14:31:39 INFO leader-settings-changed Traceback (most recent call last):
2016-10-17 14:31:39 INFO leader-settings-changed   File "/var/lib/juju/agents/unit-kubernetes-master-1/charm/hooks/leader-settings-changed", line 19, in <module>
2016-10-17 14:31:39 INFO leader-settings-changed     main()
2016-10-17 14:31:39 INFO leader-settings-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
2016-10-17 14:31:39 INFO leader-settings-changed     bus.dispatch()
2016-10-17 14:31:39 INFO leader-settings-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
2016-10-17 14:31:39 INFO leader-settings-changed     _invoke(other_handlers)
2016-10-17 14:31:39 INFO leader-settings-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
2016-10-17 14:31:39 INFO leader-settings-changed     handler.invoke()
2016-10-17 14:31:39 INFO leader-settings-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
2016-10-17 14:31:39 INFO leader-settings-changed     self._action(*args)
2016-10-17 14:31:39 INFO leader-settings-changed   File "/var/lib/juju/agents/unit-kubernetes-master-1/charm/reactive/kubernetes_master.py", line 180, in send_data
2016-10-17 14:31:39 INFO leader-settings-changed     sdn_ip = get_sdn_ip(sdn_cidr)
2016-10-17 14:31:39 INFO leader-settings-changed   File "/var/lib/juju/agents/unit-kubernetes-master-1/charm/reactive/kubernetes_master.py", line 500, in get_sdn_ip
2016-10-17 14:31:39 INFO leader-settings-changed     ip = cidr.split('/')[0]
2016-10-17 14:31:39 INFO leader-settings-changed AttributeError: 'NoneType' object has no attribute 'split'
2016-10-17 14:31:39 ERROR juju.worker.uniter.operation runhook.go:107 hook "leader-settings-changed" failed: exit status 1
2016-10-17 14:31:39 INFO juju.worker.uniter resolver.go:100 awaiting error resolution for "leader-settings-changed" hook
2016-10-17 14:31:42 INFO juju.worker.uniter resolver.go:100 awaiting error resolution for "leader-settings-changed" hook
2016-10-17 14:31:42 INFO juju.worker.uniter resolver.go:100 awaiting error resolution for "leader-settings-changed" hook
2016-10-17 14:31:42 INFO juju.worker.uniter resolver.go:100 awaiting error resolution for "leader-settings-changed" hook
2016-10-17 14:31:44 INFO juju.worker.uniter resolver.go:100 awaiting error resolution for "leader-settings-changed" hook
2016-10-17 14:31:44 INFO juju-log Reactive main running for hook leader-settings-changed
2016-10-17 14:31:45 INFO juju-log Invoking reactive handler: reactive/tls_client.py:14:store_ca
2016-10-17 14:31:45 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:209:gather_sdn_data
2016-10-17 14:31:45 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:248:start_kube_dns
2016-10-17 14:31:45 INFO juju-log Unable to determine node count, waiting until nodes are ready
2016-10-17 14:31:45 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:120:set_app_version
2016-10-17 14:31:45 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:164:push_service_data
2016-10-17 14:31:46 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:280:loadbalancer_kubeconfig
2016-10-17 14:31:46 INFO juju-log Invoking reactive handler: reactive/tls_client.py:32:store_server
2016-10-17 14:31:46 INFO juju-log Invoking reactive handler: reactive/kubernetes_master.py:171:send_data
2016-10-17 14:31:46 INFO leader-settings-changed Traceback (most recent call last):
2016-10-17 14:31:46 INFO leader-settings-changed   File "/var/lib/juju/agents/unit-kubernetes-master-1/charm/hooks/leader-settings-changed", line 19, in <module>
2016-10-17 14:31:46 INFO leader-settings-changed     main()
2016-10-17 14:31:46 INFO leader-settings-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
2016-10-17 14:31:46 INFO leader-settings-changed     bus.dispatch()
2016-10-17 14:31:46 INFO leader-settings-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
2016-10-17 14:31:46 INFO leader-settings-changed     _invoke(other_handlers)
2016-10-17 14:31:46 INFO leader-settings-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
2016-10-17 14:31:46 INFO leader-settings-changed     handler.invoke()
2016-10-17 14:31:46 INFO leader-settings-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
2016-10-17 14:31:46 INFO leader-settings-changed     self._action(*args)
2016-10-17 14:31:46 INFO leader-settings-changed   File "/var/lib/juju/agents/unit-kubernetes-master-1/charm/reactive/kubernetes_master.py", line 180, in send_data
2016-10-17 14:31:46 INFO leader-settings-changed     sdn_ip = get_sdn_ip(sdn_cidr)
2016-10-17 14:31:46 INFO leader-settings-changed   File "/var/lib/juju/agents/unit-kubernetes-master-1/charm/reactive/kubernetes_master.py", line 500, in get_sdn_ip
2016-10-17 14:31:46 INFO leader-settings-changed     ip = cidr.split('/')[0]
2016-10-17 14:31:46 INFO leader-settings-changed AttributeError: 'NoneType' object has no attribute 'split'
2016-10-17 14:31:46 ERROR juju.worker.uniter.operation runhook.go:107 hook "leader-settings-changed" failed: exit status 1
2016-10-17 14:31:46 INFO juju.worker.uniter resolver.go:100 awaiting error resolution for "leader-settings-changed" hook
```

Then again: hook failed: "kube-api-endpoint-relation-departed" for kubeapi-load-balancer

```
2016-10-17 14:32:30 INFO juju-log kube-api-endpoint:13: Invoking reactive handler: reactive/kubernetes_master.py:171:send_data
2016-10-17 14:32:30 INFO kube-api-endpoint-relation-departed Traceback (most recent call last):
2016-10-17 14:32:30 INFO kube-api-endpoint-relation-departed   File "/var/lib/juju/agents/unit-kubernetes-master-1/charm/hooks/kube-api-endpoint-relation-departed", line 19, in <module>
2016-10-17 14:32:30 INFO kube-api-endpoint-relation-departed     main()
2016-10-17 14:32:30 INFO kube-api-endpoint-relation-departed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
2016-10-17 14:32:30 INFO kube-api-endpoint-relation-departed     bus.dispatch()
2016-10-17 14:32:30 INFO kube-api-endpoint-relation-departed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
2016-10-17 14:32:30 INFO kube-api-endpoint-relation-departed     _invoke(other_handlers)
2016-10-17 14:32:30 INFO kube-api-endpoint-relation-departed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
2016-10-17 14:32:30 INFO kube-api-endpoint-relation-departed     handler.invoke()
2016-10-17 14:32:30 INFO kube-api-endpoint-relation-departed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
2016-10-17 14:32:30 INFO kube-api-endpoint-relation-departed     self._action(*args)
2016-10-17 14:32:30 INFO kube-api-endpoint-relation-departed   File "/var/lib/juju/agents/unit-kubernetes-master-1/charm/reactive/kubernetes_master.py", line 180, in send_data
2016-10-17 14:32:30 INFO kube-api-endpoint-relation-departed     sdn_ip = get_sdn_ip(sdn_cidr)
2016-10-17 14:32:30 INFO kube-api-endpoint-relation-departed   File "/var/lib/juju/agents/unit-kubernetes-master-1/charm/reactive/kubernetes_master.py", line 500, in get_sdn_ip
2016-10-17 14:32:30 INFO kube-api-endpoint-relation-departed     ip = cidr.split('/')[0]
2016-10-17 14:32:30 INFO kube-api-endpoint-relation-departed AttributeError: 'NoneType' object has no attribute 'split'
2016-10-17 14:32:30 ERROR juju.worker.uniter.operation runhook.go:107 hook "kube-api-endpoint-relation-departed" failed: exit status 1
2016-10-17 14:32:30 INFO juju.worker.uniter resolver.go:100 awaiting error resolution for "relation-departed" hook
```

and so on. It takes about 10 retries to get to a stable state. 

# Services still running

```
for service in kube-apiserver kube-scheduler kube-controller-manager; do 
   sudo systemctl stop $service; sudo systemctl disable $service 
   sudo rm /lib/systemd/system/${service}.service
done
```

# Files not removed

```
bcruser8@hnode1-15:~$ sudo find / -name "kube*" 2>/dev/null
/etc/default/kube-scheduler
/etc/default/kube-controller-manager
/etc/default/kube-apiserver
/etc/default/kube-defaults
/etc/kubernetes
/etc/ssl/certs/kubernetes-master.pem
/home/ubuntu/kubectl
/lib/systemd/system/kube-controller-manager.service
/lib/systemd/system/kube-scheduler.service
/lib/systemd/system/kube-apiserver.service
/srv/kubernetes
/usr/local/share/ca-certificates/kubernetes-master.crt
/usr/local/bin/kubectl
/usr/local/bin/kube-scheduler
/usr/local/bin/kube-controller-manager
/usr/local/bin/kube-apiserver
```

**Comment by mbruzek** [comment]
@SaMnCo Charms do not generally clean up after themselves because the cloud instances are destroyed after Juju is done with them. I understand you are using the manual provider, which has unique properties. I have not had much experience with the manual provider. I would expect a great many things to be "left over" on this machine such as juju binaries, log files, and other cloud_init files.

It seems you are suggesting we add clean up logic to the charm for when the application has been removed. I do not know of any other charms that completely remove all files on a "stop" hook, and I am not sure that is the intended behavior. What about the case where someone removes the application and wants to run analysis on the system, or back up some data?

Please let us know what you expect would happen here and how you would like it to change.

**Comment by SaMnCo** [comment]
@mbruzek I wouldn't treat this as a bug, rather an enhancement / compliance. Regardless of manual or automated, as soon as charms are colocated, machines just don't go away if you remove an application from a model. This obviously is even more true when using a manual provider. 

The definition of the remove-application feature from the help is: 

```
$ juju help remove-application
Usage: juju remove-application [options] <application>

Summary:
Remove an application from the model.

Options:
-B, --no-browser-login  (= false)
    Do not use web browser for authentication
-m, --model (= "")
    Model to operate in. Accepts [<controller name>:]<model name>

Details:
Removing an application will terminate any relations that application has, remove
all units of the application, and in the case that this leaves machines with
no running applications, Juju will also remove the machine. For this reason,
you should retrieve any logs or data required from applications and units 
before removing them. Removing units which are co-located with units of
other charms or a Juju controller will not result in the removal of the
machine.

Examples:
    juju remove-application hadoop
    juju remove-application -m test-model mariadb
```

In the current implementation, 

* Terminating all relations requires a whole lot of ```juju resolved --no-retry <name your service here>``` (up to 10 for the k8s master)
* The application is kept running, with its whole configuration unchanged. (taking a simple case of a monitoring agent, we would have this application still sending data back to its master node, making it believe it is still alive)

As far as expectations go, if I am running a set of apps in a model, and the tool I use to manage the model allows me to "remove-application", I expect the removed application to at the very least be stopped. Cleaning up files may be unnecessary, though re-installing may then end up with config files not being regenerated properly, binaries of different versions not managed properly because of file permissions and so on. 
However, the name of the feature being "removed", if feels to me destruction of application leftovers should also be part of the process. 

Again, agreed it may be a corner case in the overall grand scheme of things, this issue report was just sharing the experiment of managing a fixed set of machines on which I have little control in a Juju world.
